/** Theme pack: Ancient Lands — scene-based (dust, stone, empire, oracle, siege). */
globalThis.ACHIEVE_PRELOAD_THEME_BANKS = globalThis.ACHIEVE_PRELOAD_THEME_BANKS || {};
globalThis.ACHIEVE_PRELOAD_THEME_BANKS["ancient-lands"] = {
  title: "Ancient Lands",
  bank: {
    "predictable-starts": {
      beginner: [
        "He carried water up the hill in the heat.",
        "She had never seen a building so tall.",
        "It was louder than she had expected.",
        "They walked in a long line through the dust.",
        "The soldiers marched past without stopping.",
        "He pressed his back against the stone wall.",
        "She could not read the marks on the pillar.",
        "It smelled like smoke and something sweet.",
        "They were not allowed past the gate.",
        "He watched the fire from the top of the hill.",
      ],
      intermediate: [
        "She had been chosen and did not know why.",
        "He was the last one to cross the river.",
        "It was a city unlike anything she had seen before.",
        "They had been travelling for three days without rest.",
        "The temple was visible long before they reached it.",
        "He carried the message but did not know what it said.",
        "She kept her head down when the procession passed.",
        "It was the kind of silence that came before something broke.",
        "They were strangers here and everyone could see it.",
        "His name was on the list and he had not put it there.",
      ],
      advanced: [
        "She had stood before this council once before and lost everything.",
        "He knew the law and knew also that the law would not save him.",
        "It was a city that had been promised and, now that they had arrived, felt nothing like a promise.",
        "They had marched for forty days and the city they had come to take still stood.",
        "The order had been given before she could speak against it.",
        "He had spent his life in service to a ruler who did not know his name.",
        "She understood, reading the inscription, that the tomb had already been opened.",
        "It was not the gods they feared — it was each other.",
        "They called it peace, which was what powerful men called the quiet after they had taken what they wanted.",
        "His loyalty had been useful once; now it was a liability.",
      ],
    },
    "weak-be": {
      beginner: [
        "The wall was taller than three men.",
        "She was afraid to go inside.",
        "It was dark and cool in the temple.",
        "They were tired after the long walk.",
        "The fire was bright in the courtyard.",
        "He was the smallest one in the line.",
        "The road was long and very dusty.",
        "She was not sure which way to go.",
        "The men were dressed in armour.",
        "It was the hottest day she could remember.",
      ],
      intermediate: [
        "The city was older than anyone could say.",
        "She was the only woman in the courtyard.",
        "The walls were thick with heat and silence.",
        "He was not from here and it showed.",
        "The offering was accepted without ceremony.",
        "They were camped outside the gates by nightfall.",
        "She was aware that the guards were watching her.",
        "The inscription was worn but still readable.",
        "He was certain the messenger had not told everything.",
        "The harbour was full of ships she did not recognise.",
      ],
      advanced: [
        "The empire was old enough to have forgotten its own beginnings.",
        "She was the one who had been sent because no one else could be trusted.",
        "The decision was made before the council had been called.",
        "He was a man who had survived several rulers, which was its own kind of skill.",
        "The silence in the chamber was the silence of people who already knew the outcome.",
        "She was not permitted to speak, which was how they preferred it.",
        "The charge was clear but the evidence was not.",
        "He was useful precisely because he was not considered important.",
        "The road was the same one the army had taken twenty years before, in the other direction.",
        "They were losing, though the general was the last to admit it.",
      ],
    },
    "basic-verbs": {
      beginner: [
        "She went to the well at the edge of the settlement.",
        "He got water for the animals before it got too hot.",
        "She looked at the carvings on the stone wall.",
        "He ran when the horn sounded across the rooftops.",
        "She took the bread from the woman at the gate.",
        "He said something in a language she did not know.",
        "She went inside the dark building and looked around.",
        "He saw fire on the hill and ran back to tell someone.",
        "She made a mark in the dust with her finger.",
        "He took her hand and they went through the gate together.",
      ],
      intermediate: [
        "She walked the length of the colonnade before she said anything.",
        "He took the scroll from the shelf and looked at it in the light.",
        "She went to the marketplace before the heat of the day came.",
        "He said the name of the god three times, as the ritual required.",
        "She looked at the faces in the crowd and found no one she knew.",
        "He ran when the soldiers came through the square.",
        "She made the offering and said the words she had been taught.",
        "He took the long way around to avoid the procession.",
        "She saw the body at the side of the road and kept walking.",
        "He went to the harbour to see which ships had arrived.",
      ],
      advanced: [
        "She walked into the chamber and saw that the seal had already been broken.",
        "He took the letter from the courier and said nothing for a long time.",
        "She looked at the man across the table and made her decision.",
        "He went to the oracle not for guidance but to confirm what he had already resolved to do.",
        "She said what they needed to hear, which was not what she believed.",
        "He took the position offered and saw, immediately, its real limitations.",
        "She ran the calculation in her head and saw that the numbers did not favour survival.",
        "He made the agreement knowing he would not keep it.",
        "She went back to the inscription and looked at it again with what she now knew.",
        "He saw the army from the ridge and took a long moment before giving the order.",
      ],
    },
    repetition: {
      beginner: [
        "She carried the jar to the well. The jar was heavy. She put the jar down to rest.",
        "He climbed the steps to the temple. The steps were steep. There were many steps to climb.",
        "The soldier stood at the gate. The gate was made of wood. The soldier did not leave the gate.",
        "She drew water from the well. The well was deep. It was her job to draw water from the well every day.",
        "He wore a cloak in the sun. The cloak was white. The cloak kept the sun off his head.",
        "The fire burned in the courtyard. She watched the fire. The fire burned through the whole night.",
        "He found a stone on the path. The stone had marks on it. He kept the stone with the marks.",
        "She heard drums from inside the walls. The drums were loud. The walls were full of drums.",
        "The horse stood at the gate. The gate was open. The horse did not go through the open gate.",
        "He carried the message to the soldier. The soldier read the message. The message made the soldier go quiet.",
      ],
      intermediate: [
        "She had been to the oracle before. The oracle had spoken in riddles before. This time the oracle did not speak at all.",
        "He studied the inscription on the wall. The inscription was in a language he knew. He had seen this inscription before, in a different place.",
        "The siege had lasted forty days. Forty days was longer than anyone had expected. By the fortieth day, nobody was speaking of victory.",
        "She carried the offering to the altar. The altar was covered in ash from earlier offerings. She placed her offering beside the other offerings.",
        "He crossed the bridge before the army came. The army crossed the bridge after him. The bridge did not survive the army's crossing.",
        "The scroll contained a list of names. Her name was on the scroll. She had not expected to find her name on the scroll.",
        "He trained with the other soldiers every morning. The other soldiers did not question the training. He questioned the training every single morning.",
        "She lit the lamp in the temple. The lamp had not been lit in years. The years without a lamp had changed the feel of the temple.",
        "He was given the rank of general. The rank of general carried responsibilities he had not anticipated. He had not anticipated what the rank would eventually cost him.",
        "The wall had stood for three hundred years. Three hundred years was long enough for people to believe it would always stand. It did not stand much longer.",
      ],
      advanced: [
        "The decree had been issued in the general's name. The general had not written the decree. Writing decrees in the general's name was how the city had been run for some time.",
        "She translated the inscription carefully. The inscription described a punishment. The punishment described in the inscription was one she recognised from an earlier text.",
        "He had served the empire willingly. Willingness, however, had its limits. The limits of his willingness were about to be tested in a way he had not foreseen.",
        "The city was surrounded. A surrounded city had three choices. Of the three choices available to a surrounded city, two of them ended the same way.",
        "She was asked to choose between loyalty and survival. Loyalty had never required choosing before. Survival, she was beginning to understand, always did.",
        "The army retreated in order. An orderly retreat was still a retreat. The general who ordered the retreat knew the difference between an orderly retreat and a victory.",
        "He was given the task of recording the dead. The dead numbered more than he had been told. He recorded each of the dead and kept a copy of the record for himself.",
        "The treaty was signed in the old language. The old language had not been used in official documents for a generation. Using the old language in the treaty was a message in itself.",
        "She asked the question the council would not ask. The council's silence after her question was itself an answer. She had expected the answer, which did not make it easier.",
        "He returned to the city he had left as a young man. The city had changed. Most of the changes were things he had set in motion before he left.",
      ],
    },
    "weak-adjectives": {
      beginner: [
        "She climbed the tall steps to the top.",
        "He carried a heavy jar on his back.",
        "The old woman sat in the shade.",
        "The road was long and very hot.",
        "She found a small coin in the dust.",
        "The walls of the city were big and strong.",
        "He wore a red cloak over his armour.",
        "It was a quiet night with no wind.",
        "The dark cave was cool inside.",
        "She had a good view from the top.",
      ],
      intermediate: [
        "The old temple had been abandoned for many years.",
        "She carried a heavy offering up the steep path.",
        "The dark interior of the tomb was cold and quiet.",
        "He was a tall man who said little and moved carefully.",
        "The long march had left everyone exhausted.",
        "She found a small, strange object near the altar.",
        "The empty courtyard felt different without the crowd.",
        "He had a difficult choice and not much time.",
        "The harsh sun made the stone walls seem to glow.",
        "She sat in the quiet space between the tall columns.",
      ],
      advanced: [
        "The old general had fought in three campaigns and trusted no one.",
        "She faced a difficult decision with no good options.",
        "The dark chamber at the base of the structure had not been entered in centuries.",
        "He was a thin, calm man in a city full of loud and powerful ones.",
        "The long silence after the verdict was the most difficult part.",
        "She emerged from the empty tomb with a strange feeling she could not name.",
        "The harsh law had stood for generations and nobody had thought to question it.",
        "The heavy stone door had been sealed with something more than mortar.",
        "He looked out at the bleak plain where the battle would be fought and said nothing.",
        "She presented a powerful argument to a council that had already made up its mind.",
      ],
    },
    adverbs: {
      beginner: [
        "She walked slowly through the stone gateway.",
        "He quietly watched the soldiers march past.",
        "She carefully placed the offering on the altar.",
        "The fire burned very brightly in the dark.",
        "He ran quickly when he heard the horn.",
        "She really did not want to go inside.",
        "He bowed very low when the elder passed.",
        "She gently touched the carving on the wall.",
        "He loudly called out when he saw the ship.",
        "The old man walked very slowly up the steps.",
      ],
      intermediate: [
        "She moved silently through the colonnaded hall.",
        "He carefully unrolled the scroll on the table.",
        "She spoke very quietly so the guards would not hear.",
        "He stood completely still while they searched the room.",
        "She clearly understood what the inscription meant.",
        "He reluctantly delivered the message to the commander.",
        "She watched carefully as the ceremony began below.",
        "He bowed respectfully and said nothing further.",
        "The army moved steadily forward across the plain.",
        "She quickly calculated what would happen if she refused.",
      ],
      advanced: [
        "She delivered the verdict calmly, which was harder than it appeared.",
        "He had quietly positioned himself to be indispensable, which was its own kind of power.",
        "She spoke very precisely, because in this court imprecision was treated as confession.",
        "He moved carefully through the archive, knowing that the order of things mattered.",
        "She had clearly been expected, which meant someone had told them she was coming.",
        "He bowed deeply and smiled broadly and meant absolutely none of it.",
        "She waited patiently while the council deliberated on something that had already been decided.",
        "He read the terms carefully before refusing them very politely.",
        "The general spoke very briefly and the army understood exactly what was required.",
        "She had instinctively known, the moment she entered, that she was not going to leave freely.",
      ],
    },
    "stop-words": {
      beginner: [
        "She went up the steps and she looked at the carvings and she touched one of them.",
        "He had a jar and it was heavy and he had to carry it all the way up the hill.",
        "It was hot and the sun was very bright and there was not much shade to sit in.",
        "She saw the soldiers and she got out of the way and she waited for them to go past.",
        "He went to the well and he got some water and he went back again.",
        "There was a big wall and it went all the way around and she could not see over it.",
        "He had a cloak and it was white and he wore it over his head to keep the sun off.",
        "She went inside and it was dark and it was cool and she stayed for a while.",
        "It was a long road and they had been on it for a long time and they were very tired.",
        "He saw the fire and it was on the hill and it was very bright and he ran back.",
      ],
      intermediate: [
        "She had been to this place before and she knew her way around and she went straight to the part she needed.",
        "There was a man at the gate and he had a list and he looked at the list and he did not let her through.",
        "He had a message and it was important and he had to get it to the right person before the sun went down.",
        "It was a city that had been there for a very long time and there were a lot of things in it that were very old.",
        "She looked at the inscription and it was in a language she knew and she read it and she did not like what it said.",
        "He went to the harbour and he looked at the ships and there were a lot of them and some of them he had not seen before.",
        "There was a ceremony and it was a long one and she had to stand through all of it and she was very tired by the end.",
        "He was told to wait and so he waited and nobody came and he kept on waiting until it was dark.",
        "She made the offering and she said the words and the priest looked at her and she was not sure if she had done it right.",
        "It was a long way to the next city and there was not much water and they had to be careful about how much they used.",
      ],
      advanced: [
        "It was the kind of decree that had the look of justice about it and the feel of something else entirely and she had been around long enough to know the difference.",
        "There was a question that the council had been avoiding for some time and it was the kind of question that did not get easier the longer it went unasked.",
        "He had been given a role that seemed important and was in fact important and the importance of it was the reason he was now in the position he found himself in.",
        "She was not in a position to refuse and she knew it and the people who had given her the task knew it too and that was the whole point of asking her.",
        "The law was old and it had been applied before in similar situations and on each of those occasions it had done more harm than the thing it was meant to prevent.",
        "There was a man who had served the empire for many years and he had done things for the empire that the empire would not have wanted known and now the empire wanted him gone.",
        "She had known for some time that the information she had was the kind that could not be unknowed and that the having of it put her in a very difficult position.",
        "It was a city that had been taken before and it had been taken and then it had fallen again and each time it fell the thing that replaced it was a little worse.",
        "He was aware that the decision he was about to make was the kind that could not be undone and that the people who had put him in a position to make it had done so deliberately.",
        "There was an agreement and it had been made in good faith by some of the people involved and not in good faith by others and the difficulty was working out which was which.",
      ],
    },
    "filter-words": {
      beginner: [
        "She felt the heat of the stone through her sandals.",
        "He noticed the soldiers had stopped talking.",
        "She heard drums from somewhere inside the walls.",
        "He saw a shape move in the shadow of the gate.",
        "She felt afraid when the torches went out.",
        "He noticed the jar was cracked before he filled it.",
        "She heard someone say her name and stopped.",
        "He felt the ground shake before anyone else did.",
        "She noticed the sky had changed colour in the east.",
        "He saw the fire and knew something was wrong.",
      ],
      intermediate: [
        "She noticed the priest had not looked at her once during the ceremony.",
        "He felt the weight of the message he carried more than its physical weight.",
        "She heard what the soldier said and understood it was not a request.",
        "He realised the route he had been given was wrong in a way that was not accidental.",
        "She sensed the mood in the courtyard had shifted since morning.",
        "He watched the ships from the ridge and counted more than he had been told to expect.",
        "She thought she recognised the face of the man who had delivered the order.",
        "He knew the name on the scroll was a problem before he had finished reading it.",
        "She wondered who had decided to leave that part of the wall unguarded.",
        "He noticed the elder had stopped speaking mid-sentence and was looking past him.",
      ],
      advanced: [
        "She sensed, before the reading was finished, that her name would appear in it.",
        "He realised the treaty had been written to fail, and that the failure had been intended.",
        "She observed that the general's confidence had a quality that did not match the information available to him.",
        "He felt the moment pass in which something might have been different, and said nothing.",
        "She understood, watching the ceremony, that its purpose was not what she had been told.",
        "He knew the city would fall before the army outside its walls had worked it out.",
        "She feared that the message she carried had already been read by someone else.",
        "He noticed the silence that followed the announcement was of a different quality to ordinary silence.",
        "She remembered the last time a decree like this had been issued and what had followed.",
        "He sensed that the loyalty he had relied on had reached its limit sometime in the night.",
      ],
    },
    "sentence-structure": {
      beginner: [
        "She climbed the steps. They were steep. She got to the top.",
        "He saw the soldiers. They had shields. They marched past.",
        "The sun was hot. She found some shade. She sat down.",
        "He found a coin. It was old. He put it in his pocket.",
        "She went to the well. She filled the jar. She carried it home.",
        "The gate was open. He went through. He looked around.",
        "She heard drums. They were loud. She stopped walking.",
        "He watched the fire. It was big. It lit the sky.",
        "The building was tall. She looked up. She could not see the top.",
        "He carried the jar. It was heavy. He put it down to rest.",
      ],
      intermediate: [
        "She arrived at the city. The gate was guarded. She waited.",
        "He had a message. It was urgent. He had to find the right person.",
        "The ceremony began at dawn. She watched from a distance. She was not permitted closer.",
        "He crossed the bridge. The army was behind him. He did not look back.",
        "She found the inscription. She read it. She read it again.",
        "The walls were thick. The gate was sealed. There was no obvious way in.",
        "He spoke to the elder. The elder listened. He said nothing in reply.",
        "She reached the harbour. The ship was gone. She stood at the edge.",
        "The soldier gave him a name. He wrote it down. He did not ask questions.",
        "She carried the offering up the hill. It was steep. She arrived at the top alone.",
      ],
      advanced: [
        "She was given the order. She knew what it meant. She carried it out.",
        "He read the treaty. He understood its terms. He signed it anyway.",
        "The city had held for months. The supplies were gone. Something had to give.",
        "She found the record. It named her predecessor. It described the manner of his removal.",
        "He had served loyally. The loyalty had not been returned. He adjusted his position accordingly.",
        "She stood before the council. She stated her case. The outcome had been decided before she spoke.",
        "The general gave the order. The soldiers hesitated. He gave it again.",
        "He located the archive. He found the relevant scroll. He destroyed it before anyone could stop him.",
        "She arrived at the tomb. The seal was broken. She went in anyway.",
        "He reached the ridge. He saw the plain below. He understood that the information he had been given was wrong.",
      ],
    },
    "literary-devices": {
      beginner: [
        "The temple was big and made of stone.",
        "She walked through the gateway into the city.",
        "The soldiers stood in a line outside the building.",
        "It was hot and there was a lot of dust.",
        "He heard the sound of drums in the distance.",
        "The fire was bright and lit up the sky.",
        "She touched the carving on the wall.",
        "The road was long and went over a hill.",
        "He looked at the ships in the harbour.",
        "The old man sat in the shade and watched people go past.",
      ],
      intermediate: [
        "The city rose from the plain and could be seen from far away.",
        "She walked through the colonnaded hall without speaking.",
        "The crowd parted when the procession came through.",
        "He stood at the edge of the ridge and looked at the valley below.",
        "The inscription on the wall was old and hard to read.",
        "She made the offering and waited to see what would happen.",
        "The harbour was full of ships and the sound of water and rope.",
        "He entered the archive and found what he had come for.",
        "The temple sat at the top of the hill and could be seen from everywhere.",
        "She crossed the plain in the early morning before the heat came.",
      ],
      advanced: [
        "The city had been built to last and had lasted longer than intended.",
        "She crossed the threshold and the door was closed behind her.",
        "The general addressed the army before the battle began.",
        "He sat in the chamber and read through the accounts of the previous administration.",
        "The oracle spoke and the words were written down and taken away.",
        "She read the terms of the agreement and decided what she was going to do.",
        "The army moved across the plain in the early light.",
        "He attended the council and said what he had come to say.",
        "The temple had stood for five hundred years and looked it.",
        "She accepted the role that was offered and began immediately to plan.",
      ],
    },
    "paragraph-cohesion": {
      beginner: [
        "She went to the well. It was sunny. The water was cold. She liked the sound it made. She went home.",
        "He saw the soldiers. They were tall. He wanted to be a soldier. His sandal was broken. He watched them go past.",
        "The fire was bright. She was hungry. It lit up the whole sky. The night was warm. She sat near it.",
        "He climbed the steps. There were many steps. He was good at climbing. His jar was heavy. He got to the top.",
        "She looked at the carving. It was old. Her mum was waiting. The stone was rough. She touched it anyway.",
        "The drums were loud. He had never heard drums before. He was thirsty. They stopped after a while. He went back inside.",
        "She found a coin. It was small. Her brother wanted to see it. It had a face on it. She kept it.",
        "He watched the ship come in. It was big. He had never been on a ship. The sailors were loud. He went home for dinner.",
        "The gate was open. She went through. It was very hot. She had not been here before. She looked around.",
        "He gave the jar to the elder. The elder was old. He said thank you. It was nearly dark. He ran home.",
      ],
      intermediate: [
        "She arrived before dawn. The city was not what she had been told. She found the gate without help. Someone was watching from above. She went in anyway.",
        "He was given a task. The task had not been explained properly. He asked for clarification and was told to proceed. He did not understand its purpose. He completed it.",
        "The ceremony lasted most of the morning. She stood through all of it. Her role in it was unclear. The elder acknowledged her once. She was told to leave before it ended.",
        "He found the inscription on the third day. It was in a dialect he knew only partly. He spent the night trying to decipher it. He was interrupted twice. He did not finish.",
        "She crossed the bridge at midday. It was narrower than expected. A soldier stopped her halfway. She gave the name she had been told to give. She was let through.",
        "He delivered the message as instructed. The recipient was not who he had expected. The message was read in silence. He was not told its contents. He was dismissed without thanks.",
        "The harbour was busy when she arrived. She counted twelve ships she did not recognise. She needed to find one specific vessel. Someone offered to help. She declined.",
        "He climbed to the ridge before the others were awake. The plain below was still dark. He could see fires where the army was camped. His orders were to report what he saw. He was not sure his report would be believed.",
        "She was brought before the elder council. She had prepared what she would say. The first question was not what she had expected. The second was worse. She answered both.",
        "He reached the archive on the final day before it was sealed. The record he needed was not where it was supposed to be. He searched for two hours. He found it in the wrong section. He was not sure if that was an accident.",
      ],
      advanced: [
        "The decree was issued in the old form, which meant it could not be appealed. She had been told about it three days before it was made public. She had spent those three days trying to prevent it. She had not succeeded. She was still deciding what to do.",
        "He had worked in the archive for twenty years. He knew where everything was kept. He knew what was missing and why. He had never told anyone. Today he was going to tell someone.",
        "She was offered a position in the new administration. The position came with conditions she was not shown in advance. When she read them she understood why. She accepted anyway. She was already planning her response.",
        "The treaty had been written by someone who knew it would be broken. The breaking of it had been intended from the start. She had the correspondence to prove it. The correspondence had been given to her by the person who had written the treaty. She did not know what to do with that.",
        "He had served the previous ruler and the ruler before that. Each transition had required him to forget certain things. He had become very good at forgetting. He was less good at being forgiven for what he remembered. Today he was going to remember something.",
        "The city had been besieged before and had survived. The previous siege had lasted eight months. This one had already lasted nine. The general inside had fought in the previous siege. He knew exactly what month this was.",
        "She found the body at the base of the archive stair. She recognised him. She did not raise the alarm. She went first to find what he had come to retrieve. She found it and took it. Then she raised the alarm.",
        "The oracle had spoken. The words had been recorded. The recording was given to the council. The council's interpretation was not the one she had heard with her own ears. She had also been in the room.",
        "He was told his predecessor had resigned. He had known his predecessor well. His predecessor was not the kind of man who resigned. He accepted the role. He kept this thought entirely to himself.",
        "The siege ended on a morning with no wind. The gates were opened from the inside. This was presented as a surrender. She had been the one to open them. She did not call it that.",
      ],
    },
    "narrative-types": {
      beginner: [
        "She went to the well. She filled the jar. She carried it back. She put it down.",
        "He saw the soldiers. He stepped aside. They passed. He kept walking.",
        "She climbed the steps. She reached the top. She looked around. She came back down.",
        "He found the coin. He picked it up. He looked at it. He put it in his pocket.",
        "She heard the drums. She stopped. She listened. She walked on.",
        "He went to the gate. He knocked. Someone answered. He went inside.",
        "She made the offering. She said the words. She stepped back. She left.",
        "He carried the message. He found the soldier. He gave it to him. He walked away.",
        "She saw the fire. She ran to find someone. She told them. They went to look.",
        "He crossed the bridge. He reached the other side. He looked back. He kept walking.",
      ],
      intermediate: [
        "She reached the city at dawn. She found the gate open. She went through. She looked for the building she needed.",
        "He received the order. He read it. He gave the necessary instructions. He waited for them to be carried out.",
        "She crossed the plain in the early morning. She reached the walls by midday. She found the entrance. She went in.",
        "He attended the ceremony. He watched the proceedings. He made his offering. He left.",
        "She found the inscription. She studied it. She made a copy. She left the archive.",
        "He spoke to the elder. He made his request. He was refused. He thanked the elder and left.",
        "She reached the ridge. She looked at the plain below. She counted the campfires. She went back to report.",
        "He was given the message. He memorised it. He destroyed it. He went to deliver it.",
        "She waited at the harbour. The ship came in. She found the captain. She gave him what she had brought.",
        "He entered the chamber. He took what he had come for. He left everything else as it was. He sealed the entrance.",
      ],
      advanced: [
        "She received the summons. She prepared her response. She attended the council. She stated her position. She was dismissed.",
        "He identified the threat. He assessed his options. He made a decision. He gave the order. He did not wait to see the outcome.",
        "She found the document. She read it. She understood what it meant. She made a copy. She replaced the original.",
        "He crossed the border. He located the contact. He received the information. He returned. He reported only part of what he had been told.",
        "She accepted the terms. She signed what was required. She left the chamber. She began immediately to work against them.",
        "He attended the ceremony as instructed. He observed everything. He said nothing unnecessary. He left. He wrote down what he had seen.",
        "She reached the archive before it was sealed. She found the relevant record. She removed three pages. She left the rest. She destroyed the pages that evening.",
        "He located the general. He delivered the message. He waited for a reply. There was no reply. He went back without one.",
        "She stood before the assembly. She made her statement. She answered the questions put to her. She was thanked. She was escorted out.",
        "He accepted the position offered. He learned everything he could from it. He waited for the right moment. He acted. He did not look back.",
      ],
    },
    "author-stems": {
      beginner: [
        "Without warning, the drums ...",
        "All of a sudden, the gates ...",
        "From the top of the hill, ...",
        "Before she could stop herself, she touched ...",
        "Just as he reached the gate, ...",
        "For a moment, the crowd ...",
        "Out of nowhere, a soldier ...",
        "Right at that second, she saw ...",
        "Deep inside the temple, something ...",
        "At the very top of the steps, he found ...",
      ],
      intermediate: [
        "Without warning, the fire spread to ...",
        "Deep inside, she knew the message meant ...",
        "What nobody had noticed was the moment when ...",
        "For a moment, the whole city seemed to ...",
        "Long before the army arrived, she had already ...",
        "Behind the sealed door, something ...",
        "With hands she could not quite keep still, she opened ...",
        "Somewhere between the gate and the archive, she realised ...",
        "In the space of a single moment, everything changed because ...",
        "What she had not prepared for was the way the elder looked at her when ...",
      ],
      advanced: [
        "Somewhere between arriving as a servant and leaving as something else, she had ...",
        "What nobody on the council was willing to name was the fact that ...",
        "Long before the siege began, he had already calculated that ...",
        "With a composure she had spent years learning, she told them ...",
        "Deep inside, beneath the performance of loyalty, she understood that ...",
        "What the treaty could not account for was the moment when ...",
        "In the years that followed, historians would argue about whether ...",
        "Somewhere between the version she gave in her testimony and what she had actually seen, the truth ...",
        "Without ceremony and without witnesses, she ...",
        "What she had built, across years of careful and costly patience, was ...",
      ],
    },
    "information-adders": {
      beginner: [
        "She carried the jar.",
        "He watched the soldiers.",
        "The gate was open.",
        "She made the offering.",
        "He crossed the bridge.",
        "The fire burned all night.",
        "She climbed the steps.",
        "He heard the drums.",
        "The ship came into the harbour.",
        "She touched the carving.",
      ],
      intermediate: [
        "She arrived at the city before dawn.",
        "He delivered the message to the wrong person.",
        "The ceremony lasted longer than expected.",
        "She found the inscription on the third day.",
        "He crossed the plain without stopping.",
        "The elder refused her request.",
        "She reached the archive before it was sealed.",
        "He stood at the ridge and looked at the plain below.",
        "The gate was guarded on both sides.",
        "She made the copy before anyone could stop her.",
      ],
      advanced: [
        "She accepted the terms without negotiation.",
        "He removed the pages before the archive was sealed.",
        "The decree was issued in the old form.",
        "She stood before the council without preparation.",
        "He identified the contact at the harbour.",
        "The treaty was signed by people who did not intend to keep it.",
        "She entered the chamber and found the seal already broken.",
        "He gave the order before the full situation was clear.",
        "The general addressed the army before the information reached him.",
        "She left the city before the gates were closed.",
      ],
    },
  },
};
