/** Theme pack: Stranded — survival, coast, signal fires; level bands Y3 / Y4–5 / Y6. */
globalThis.ACHIEVE_PRELOAD_THEME_BANKS = globalThis.ACHIEVE_PRELOAD_THEME_BANKS || {};
globalThis.ACHIEVE_PRELOAD_THEME_BANKS["stranded"] = {
  title: "Stranded",
  bank: {
    "predictable-starts": {
      beginner: [
        "He sat on the rocks and waited.",
        "She could not see anyone on the beach.",
        "It was getting dark very quickly.",
        "They had no food left at all.",
        "The water was too cold to swim in.",
        "He called out but nobody came.",
        "She found a stick to make a shelter.",
        "It started to rain on them.",
        "They huddled together to keep warm.",
        "The sky turned grey and the wind picked up.",
      ],
      intermediate: [
        "He searched the treeline for any sign of movement.",
        "She had been walking for hours without finding fresh water.",
        "It was the third night and nobody had come.",
        "They built a fire before the sun went down completely.",
        "The smoke rose but there was nobody to see it.",
        "He climbed to the highest point he could reach.",
        "She wrapped the torn jacket around her shoulders and waited.",
        "It was impossible to tell which direction the shore was.",
        "They decided to move before the storm reached them.",
        "There was nothing on the horizon except open water.",
      ],
      advanced: [
        "He had rationed what little remained with careful precision.",
        "She understood now that rescue was not coming quickly.",
        "It was not fear that kept her moving but something closer to habit.",
        "They had stopped arguing about the decision two days ago.",
        "The signal fire had burned through the last of the dry wood.",
        "He mapped the coastline in his mind, looking for anything useful.",
        "She found herself thinking about small things — the weight of a cup, the smell of bread.",
        "It occurred to him that nobody at home knew to look here.",
        "They had survived worse, though neither could quite remember when.",
        "There was a moment, just before dawn, when everything felt possible again.",
      ],
    },

    "weak-be": {
      beginner: [
        "Across the beach, the sand was empty for miles.",
        "After the storm, Liam was cold and soaked.",
        "Beside the rocks, the fire was almost out.",
        "Under the palms, Mia was scared but quiet.",
        "Beyond the camp, the trees were too thick to enter.",
        "By midday, Noah was hungry and thirsty.",
        "Above the beach, the cliff was too steep to climb.",
        "Without a map, the children were lost by sunset.",
        "Inside her shoes, sand and water were trapped.",
        "Near the horizon, the sky was turning orange."
      ],
    
      intermediate: [
        "Beyond the headland, the nearest town was further than anyone had guessed.",
        "Inside the bush, something had been moving for several minutes.",
        "Across the river, the current was too strong to risk.",
        "After hours of walking, Jayden was exhausted and still shelterless.",
        "Above the treeline, the smoke was barely visible.",
        "Without dry clothes, the group wasn't prepared for the cold night.",
        "Beside the empty creek bed, her water bottle had already run dry.",
        "Behind them, the path had been swallowed by rising water.",
        "Among the group, Leo was the only one who still believed help would come.",
        "Over the island, the clouds were gathering before rain."
      ],
    
      advanced: [
        "By the second night, the situation was more serious than anyone had admitted.",
        "Within the next few hours, every choice would be critical.",
        "Between the plan and reality, a dangerous gap had opened.",
        "Around the campfire, the others were watching Kai because he hadn't panicked yet.",
        "Across the unfamiliar terrain, the map was becoming less reliable.",
        "Beneath her calm voice, Ava's confidence was beginning to thin.",
        "Behind them, the distance they had covered was smaller than the journey ahead.",
        "Despite his steady tone, Mason had become uncertain about the route.",
        "Beside the dying fire, their only real asset was almost gone.",
        "After three days inland, the choices from day one were starting to matter.",
      ],
    },

    "basic-verbs": {
      beginner: [
        "She went to the edge of the water and looked out.",
        "He got some sticks and made a pile for the fire.",
        "They saw a light in the distance and ran toward it.",
        "She said they should stay together and not move.",
        "He looked around and saw nothing but trees.",
        "She took off her jacket and made a bed from it.",
        "They went up the hill to look for the track.",
        "He got some rocks and made a circle for the fire.",
        "She looked at the sky and said it would rain.",
        "He ran to the top of the dune and looked out.",
      ],
      intermediate: [
        "She went along the cliff edge looking for a way down.",
        "He got a long branch and made a marker in the sand.",
        "They saw the smoke and said it might be a camp.",
        "She looked at the map and said they had gone the wrong way.",
        "He took the last of the water and made sure everyone got some.",
        "They went down to the river and looked for somewhere to cross.",
        "She said they needed to make a decision before it got dark.",
        "He got some bark and made a rough shelter against the rock.",
        "They saw something moving in the water and went to have a look.",
        "She took a deep breath and said they would be fine.",
      ],
      advanced: [
        "She went back over the route in her mind, looking for the moment it had gone wrong.",
        "He said nothing but his expression said everything the group needed to know.",
        "They saw the helicopter and ran toward the clearing, waving anything they had.",
        "She took stock of what remained and said they needed to be careful.",
        "He went to the far side of the ridge and looked for running water.",
        "They made a decision to move south and said they would not second-guess it.",
        "She looked at each of them in turn and said they had made it this far.",
        "He got what little food remained and made sure the youngest ate first.",
        "They saw the tracks and went to follow them before the light went.",
        "She took a long breath and said the only thing left to do was keep moving.",
      ],
    },

    "repetition": {
      beginner: [
        "She found some water. The water was cold. She drank the cold water quickly.",
        "He built a fire. The fire was small. He fed the fire with dry sticks.",
        "They saw a track. The track went into the bush. They followed the track.",
        "She heard a sound. The sound came again. She moved toward the sound.",
        "He found some fruit. He wasn't sure about the fruit. He left the fruit on the ground.",
        "The sun went down. When the sun was gone it got cold. She missed the sun.",
        "She made a shelter. The shelter was small. She crawled into the shelter.",
        "He called for help. He kept calling for help. His voice hurt from calling for help.",
        "They found the creek. The creek was shallow. They followed the creek downstream.",
        "She had a plan. The plan was simple. She told everyone the plan.",
      ],
      intermediate: [
        "She spotted a trail through the scrub. The trail was faint. Following the trail was their best option.",
        "He gathered wood for the fire. The fire took a long time to start. Once the fire was going, nobody wanted to leave it.",
        "They reached the ridge as the sun was setting. From the ridge they could see the coast. The ridge would be their camp for the night.",
        "She rationed the food carefully. The food would last two more days. She didn't tell the others how little food remained.",
        "He found a pool of water caught in the rock. The water looked clean. He cupped the water in his hands and drank.",
        "They heard a sound from the treeline. The sound came again, closer. They held still and listened to the sound.",
        "She marked the tree with a stone. The marked tree would help them find their way back. She marked a second tree for safety.",
        "He scanned the horizon for any signal. There was no signal to the east. He turned and scanned for a signal in the other direction.",
        "The shelter held through the first half of the night. By the second half the shelter had begun to leak. They rebuilt the shelter before morning.",
        "She kept her fear to herself. Showing her fear would not help anyone. She was not the only one hiding her fear.",
      ],
      advanced: [
        "She made a decision to head toward the coast. The decision was based on very little information. A bad decision, she knew, was still better than no decision at all.",
        "He estimated they had enough supplies for three days. Three days was not long. He began planning what three days could realistically achieve.",
        "The group's morale had held through the first night. Morale was harder to manage than food or water. She watched the morale of each person carefully.",
        "She identified the peak as their best landmark. From the peak they would be able to see the full scope of what they faced. She did not tell them how far the peak actually was.",
        "He noted the direction of the wind. Wind direction mattered for the fire. It also mattered for carrying sound. He kept checking the wind.",
        "They had one working torch between them. The torch battery would not last another full night. Whoever held the torch held a kind of power, and they all knew it.",
        "She found a path leading down from the escarpment. The path was narrow and the path was steep. She tested the path before she let anyone else follow.",
        "He counted their resources twice. Counting the resources again changed nothing. The act of counting the resources gave him something to do with his hands.",
        "The cold was manageable during the day. At night the cold was a different problem. She had underestimated the cold every night so far.",
        "They agreed on a plan before the light failed. The plan required trust. She was not sure the plan had enough of either.",
      ],
    },

    "weak-adjectives": {
      beginner: [
        "It was a cold night with a dark sky.",
        "She found a small cave near the big rocks.",
        "The old path was hard to see in the long grass.",
        "He had a good idea about where to find water.",
        "The empty beach went on for a long way.",
        "She had a heavy bag on her back.",
        "It was a strange sound that came from the dark trees.",
        "He found a nice flat rock to rest on.",
        "The cold water made her feel a little better.",
        "It was a big hill and it was hard to climb.",
      ],
      intermediate: [
        "The cold wind made the long night feel even harder.",
        "She found a small hollow in the big cliff face.",
        "It was a difficult climb up the steep and empty hillside.",
        "He had a heavy feeling that they had made a bad decision.",
        "The dark water was cold and the current was strong.",
        "She looked at the long, empty stretch of coast and felt small.",
        "The old signal mirror was good enough to catch the light.",
        "He built a small fire in the empty hollow of the rock.",
        "It was a tense wait through the cold and dark night.",
        "The heavy clouds made the already dark sky look bleak.",
      ],
      advanced: [
        "The cold, empty landscape offered nothing that could be called good shelter.",
        "She faced a difficult choice between the long coastal route and the dark inland track.",
        "The heavy silence of the bush was strange in a way she found hard to explain.",
        "He had made a bad decision and its heavy consequences were now impossible to ignore.",
        "The long wait had worn down even the most calm and positive members of the group.",
        "She built a small fire in the dark hollow, knowing it was a good but temporary solution.",
        "The old map showed a difficult track that cut through the long, empty central plain.",
        "He felt a tense, cold dread settle in as the dark sky thickened overhead.",
        "The big question was whether the empty valley would give them anything useful.",
        "She assessed their position with a heavy and difficult honesty that nobody else seemed ready for.",
      ],
    },

    "adverbs": {
      beginner: [
        "She carefully picked up the dry sticks for the fire.",
        "He walked very slowly because his feet were sore.",
        "She looked nervously into the dark bush.",
        "They huddled very closely together to stay warm.",
        "He quietly listened for any sound from outside.",
        "She called out very loudly so someone might hear.",
        "He really wanted to find fresh water soon.",
        "She carefully wrapped the jacket around the youngest one.",
        "They moved very slowly so they wouldn't get lost.",
        "He suddenly stopped and listened very carefully.",
      ],
      intermediate: [
        "She carefully rationed the last of the water between them.",
        "He moved very cautiously along the narrow cliff ledge.",
        "She spoke very calmly so the others wouldn't panic.",
        "They walked steadily through the scrub, trying hard not to trip.",
        "He silently counted the hours until sunrise.",
        "She looked desperately for any landmark she could recognise.",
        "He breathed very slowly and tried really hard to think clearly.",
        "They listened intently for the sound of the helicopter returning.",
        "She very carefully arranged the signal stones on the open ground.",
        "He moved quickly but quietly toward the sound of running water.",
      ],
      advanced: [
        "She spoke very deliberately, choosing each word carefully so as not to alarm the group.",
        "He moved methodically through the available options, weighing each one slowly and carefully.",
        "She had rationed so precisely that there was very little room for any further error.",
        "He waited absolutely still, listening very intently for any sound that did not belong.",
        "She assessed the situation very calmly, though internally she was deeply and genuinely afraid.",
        "They had moved steadily south all morning, constantly and carefully checking the sun's position.",
        "He spoke very quietly, as though saying it too loudly might make it finally and irreversibly real.",
        "She had been trying very hard not to think too clearly about how long they had been out here.",
        "He signalled silently and very urgently to the others to stop moving completely.",
        "She breathed very slowly, counting carefully, until the panic retreated far enough to think.",
      ],
    },

    "stop-words": {
      beginner: [
        "She went to the edge of the water and she looked out and there was nothing there.",
        "He had a look around and it was dark and there were no lights anywhere.",
        "They were cold and they were hungry and they did not know what to do.",
        "She found some wood and she made a pile of it and then she tried to make a fire.",
        "He went up the hill and he had a look and then he came back down.",
        "It was really cold and she was really tired and she really wanted to go home.",
        "They heard a sound and it was coming from the trees and they were not sure what it was.",
        "He got some rocks and he made a circle and then he put the sticks inside it.",
        "She was at the beach and it was getting dark and she did not have a torch.",
        "They walked and they walked and they could not find the track and then it got dark.",
      ],
      intermediate: [
        "It was a situation where they had to make a decision about which way to go and they were not sure which way was the right one.",
        "She had a look at the map and it was not very clear and she was not sure that it was going to be of any use to them.",
        "There was a lot of cloud cover and it was making it really hard to tell which direction they were heading in.",
        "He went down to the river and had a look at it and it was too wide and too deep and there was no way they could get across it.",
        "The fire was going out and they needed more wood and it was too dark to go and get any more from the trees.",
        "She was not sure whether they should stay where they were or keep moving and she did not want to make the wrong call.",
        "There was a sound coming from somewhere in the bush and it was hard to tell what it was or how far away it was.",
        "He told the others that they would be fine and that someone would come and find them and that they just had to wait.",
        "It had been a long time and they were starting to get really worried and they were not sure what the best thing to do was.",
        "She found a spot that was out of the wind and it was not much but it was better than where they had been before.",
      ],
      advanced: [
        "It was a situation that none of them had been prepared for and it was becoming increasingly clear that the things they had assumed would help them were not going to be of much use.",
        "There was a part of her that was aware that the decisions she was making were not based on a great deal of solid information and that this was a problem.",
        "He had been trying to keep the mood of the group up but it was getting harder to do that as the hours went on and nothing changed.",
        "She was of the view that they should stay put and wait but there were others who felt that they should be doing something more active.",
        "The thing about the situation was that it was hard to know what the right call was because there were so many factors they could not properly assess or control.",
        "He went back over the route they had taken and tried to work out at what point things had started to go in the wrong direction.",
        "There was not a lot of food left and what they did have was not going to be enough to keep them going for more than another day or so.",
        "She was in the position of having to manage the feelings of the people around her at the same time as trying to work out what the best course of action was.",
        "It was getting to the point where they were going to have to accept that the situation was more serious than any of them had been willing to say out loud.",
        "There was a sense among the group that something needed to happen and that if it did not happen soon then things were going to get a great deal worse.",
      ],
    },

    "filter-words": {
      beginner: [
        "She felt cold and scared when the sun went down.",
        "He saw something move in the trees and stopped.",
        "She heard the sound of water somewhere nearby.",
        "He felt his stomach growl because he was so hungry.",
        "She noticed the sky was getting darker very fast.",
        "He thought he heard someone calling from far away.",
        "She felt the ground was damp under her feet.",
        "He saw a light flash on the water and pointed.",
        "She felt something crawl across her hand in the dark.",
        "He noticed the fire was almost out and grabbed more sticks.",
      ],
      intermediate: [
        "She noticed the temperature had dropped sharply since sunset.",
        "He felt certain he had heard a helicopter somewhere to the north.",
        "She saw the smoke rising and wondered if anyone would spot it.",
        "He realised the path had been leading them in a wide circle.",
        "She heard branches snapping and felt her pulse quicken.",
        "He noticed the others were watching him, waiting for a decision.",
        "She felt the first drops of rain and knew what was coming.",
        "He thought he recognised the ridge from when they had started out.",
        "She sensed the group's mood shifting as the second night closed in.",
        "He watched the horizon and felt the first flicker of genuine doubt.",
      ],
      advanced: [
        "She realised, in a way she could not quite explain, that they had been heading the wrong way for hours.",
        "He felt the weight of the group's dependence on him as something almost physical.",
        "She noticed the change in the light and understood they had less time than she had planned for.",
        "He sensed that the group's confidence in him was not as solid as it had been that morning.",
        "She heard the silence where there had been sound and knew something had shifted.",
        "He observed the way the youngest one moved and understood the exhaustion was becoming serious.",
        "She felt something close to certainty that they were being watched, though she said nothing.",
        "He realised the decision had been made for them by the weather, which was almost a relief.",
        "She noticed the way he held his arm and understood he had been hiding an injury.",
        "He felt the cold settle in like a presence and knew the night would be the hardest yet.",
      ],
    },

    "sentence-structure": {
      beginner: [
        "She was cold. The wind blew. She had no jacket.",
        "He found a cave. It was small. He went inside.",
        "The fire went out. It was dark. She was scared.",
        "They heard a sound. They stopped. They listened.",
        "He was hungry. There was no food. He drank some water.",
        "She saw a bird. It flew away. She watched it go.",
        "The rain came. They got wet. They found a tree.",
        "He built a shelter. It was wobbly. It fell down.",
        "She called out. Nobody answered. She tried again.",
        "They were tired. They stopped walking. They sat down.",
      ],
      intermediate: [
        "The sun went down. The temperature dropped. They were not prepared for it.",
        "She found the creek. It was moving fast. She decided not to cross.",
        "He lit the fire. The smoke was thick. He hoped someone would see it.",
        "They reached the ridge. The view was wide. None of it looked familiar.",
        "She had a plan. She explained it quickly. Not everyone agreed.",
        "The food was running low. They had two days left. Nobody said anything.",
        "He checked the map. The scale was wrong. He folded it away.",
        "She heard the helicopter. It passed overhead. It did not circle back.",
        "They built a signal on the flat ground. It took an hour. The cloud came in.",
        "He looked at the others. They were watching him. He made a decision.",
      ],
      advanced: [
        "She assessed their position. The news was not good. She kept her expression steady.",
        "He had made a mistake on day one. It had cost them half a day. He had not mentioned it.",
        "The group had held together. The tension was there. It had not broken anything yet.",
        "She found the source of the sound. It was nothing useful. She turned back.",
        "He rationed the water. It would last three days. Three days was not enough.",
        "They reached the clearing. The helicopter had gone. The fire had worked but the timing had not.",
        "She identified two options. Both carried risk. She chose the one with the faster outcome.",
        "He had kept his doubt private. It had cost him sleep. It had probably helped the group.",
        "The signal fire burned through the night. Nobody came. They started again in the morning.",
        "She made the call. It turned out to be right. She would never fully know why.",
      ],
    },

    "literary-devices": {
      beginner: [
        "The wind blew and the trees moved.",
        "She was cold and she was tired.",
        "The fire made light in the dark.",
        "He drank the water from the rock.",
        "The waves were loud on the shore.",
        "She put sticks on the fire.",
        "The sky was dark and it was late.",
        "He sat and waited for someone to come.",
        "The bush was thick and hard to walk through.",
        "She looked at the stars and waited.",
      ],
      intermediate: [
        "The coast stretched out in both directions without any sign of life.",
        "She sat beside the fire as the temperature dropped.",
        "The smoke rose above the treeline into the still air.",
        "He reached the top of the ridge and looked out.",
        "The sound of the creek carried through the darkness.",
        "She turned the signal mirror toward the sun and waited.",
        "The night was long and the cold settled in.",
        "He watched the horizon as the light faded.",
        "The shelter held against the wind but barely.",
        "She pressed on through the scrub until the ground levelled out.",
      ],
      advanced: [
        "She stood at the edge of the escarpment and took in the full extent of what they faced.",
        "The fire threw light across the faces of the group.",
        "He had made a decision and now they were living inside it.",
        "The silence after the helicopter passed was difficult to sit with.",
        "She rationed the last of the food with a precision that surprised even her.",
        "The cold moved through the camp in the hours before dawn.",
        "He laid out the facts for the group without softening any of them.",
        "The landscape offered nothing that looked like progress.",
        "She returned to the same thought throughout the night.",
        "The morning came and with it a chance to begin again.",
      ],
    },

    "paragraph-cohesion": {
      beginner: [
        "She found a path. Her shoes were wet. The trees were tall. She kept walking. A bird called out.",
        "He was thirsty. The clouds looked heavy. He found a leaf. It was green. He kept going.",
        "They stopped walking. The fire was warm. Her bag was heavy. Someone laughed. It was cold.",
        "She heard a sound. The ground was soft. He was tired. There were rocks. She looked up.",
        "He built a fire. Her hands were cold. The sticks were damp. There was a creek. It worked in the end.",
        "She was scared. The sky was orange. He found a stick. They were hungry. The wind picked up.",
        "They sat together. It was night. Her socks were dry. He closed his eyes. The stars came out.",
        "He called for help. The beach was long. She was thirsty. There were shells on the sand. Nobody answered.",
        "She had a plan. His knee hurt. The sun was high. There was no track. She explained it anyway.",
        "They found water. It was cold. Her hair was wet. He said something. They kept going.",
      ],
      intermediate: [
        "The fire was almost out. She had found a path that morning. He was still sleeping. The temperature had dropped overnight. They needed to decide soon.",
        "He checked the map twice. Her water bottle was empty. The ridge was close. It had rained all night. He folded the map away.",
        "She signalled with the mirror. The helicopter was heading west. His boots had a hole in them. The sun was directly above. The helicopter did not change course.",
        "They had walked for six hours. The blisters were getting bad. Nobody had said much since noon. The track had disappeared two hours ago. There was still no high ground ahead.",
        "He rationed the food carefully. She was good at starting fires. The coast was further than the map suggested. One of them had a twisted ankle. He divided the food into four equal portions.",
        "She built a lean-to against the fallen tree. He had found the creek that afternoon. Her jacket was soaked through. The temperature was dropping. The shelter was not big enough for all of them.",
        "The signal worked. He had laid it out at midday. Her hands were badly scratched from the rocks. The stones had been heavy. They heard the plane change direction overhead.",
        "She made the decision to stay put. His morale was low. The food was nearly gone. A lizard ran across the rock beside her. She told the group in the clearest terms she could.",
        "He found the track. It was faint but it was there. She had been right about the direction. Her feet were badly blistered. He called out to the others without looking back.",
        "The night was the hardest so far. She had kept the fire going. He had barely slept. The temperature had gone below zero. In the morning they did not talk about it.",
      ],
      advanced: [
        "She identified the ridge as their best option. The group's morale had held through two nights. He had been quiet since the argument at the creek. The map was unreliable at this scale. She made the call regardless.",
        "He had kept the doubt to himself since the first evening. The fire had gone out twice in the night. She had asked him twice if he was certain. The question of the route was still unresolved. He answered in the same way both times.",
        "The group reached the clearing just after noon. She had not eaten since the previous morning. The signal had been visible from three hundred metres. He had designed it from memory. They heard the aircraft while they were still building it.",
        "She had rationed with precision throughout. The food had lasted four days, not three. He had not been fully honest about how much he had eaten on day one. The others had not noticed. She had.",
        "The decision to move south had been made quickly. The reasoning had been sound. The terrain had proved more difficult than anticipated. They were two kilometres from where the map said they should be. Nobody had raised this yet.",
        "He had held the group's trust through the worst of it. She had played a large part in that and he knew it. The third night had broken something between them that neither had named. They worked together with the same efficiency. The warmth was not the same.",
        "The signal fire had been built on open ground for visibility. She had chosen the site carefully. The wind had changed direction at the worst moment. The smoke had gone into the treeline. The aircraft had passed at three hundred metres.",
        "She made the call to leave the camp before first light. Her reasoning was sound on paper. He had disagreed the night before. By midday she had been proven right. He did not say so and she did not require it.",
        "They had been prepared for two days. They were now on day five. The gap between what they had brought and what they needed had been clear from day two. Nobody had said this until now. Saying it did not help but it also did not hurt.",
        "He found the trail marker half-buried under leaf litter. She had said there would be something at the base of the escarpment. He had not believed her. The marker confirmed the route she had argued for since day one. He showed it to her without speaking.",
      ],
    },

    "narrative-types": {
      beginner: [
        "She walked to the water. She looked out. She sat down. She waited.",
        "He found some sticks. He made a pile. He lit the fire. It burned.",
        "She heard a sound. She stopped. She looked around. She kept going.",
        "He climbed the hill. He looked out. He saw the sea. He came down.",
        "She built a shelter. She got inside. She closed her eyes. She slept.",
        "He was thirsty. He found a creek. He drank some water. He felt better.",
        "She saw a light. She ran toward it. She called out. Nobody was there.",
        "He got cold. He sat by the fire. He put more sticks on. He felt warmer.",
        "She lost the track. She stopped. She thought. She chose a direction.",
        "He was scared. He breathed slowly. He got up. He kept moving.",
      ],
      intermediate: [
        "She identified the high ground. She climbed it. She scanned the area. She came back down. She reported what she had seen.",
        "He gathered what was left of the food. He divided it up. He handed each portion over. He kept the smallest share.",
        "She heard the aircraft. She grabbed the mirror. She angled it toward the sound. The plane passed. She lowered the mirror.",
        "He checked the group. Everyone was upright. He counted them. He moved to the front. He set the pace.",
        "She found the creek. She tested the current. She looked for a crossing point. She found one. She went first.",
        "He assessed the shelter. It was inadequate. He dismantled it. He rebuilt it. He tested it before letting anyone inside.",
        "She looked at the map. She located their position as best she could. She identified a landmark. She set a heading. She started walking.",
        "He made a fire. It went out. He made another. It held. He sat beside it until the others were asleep.",
        "She rationed the water. She wrote down the amounts. She called everyone together. She explained the situation clearly. She answered the questions that followed.",
        "He reached the ridge. The view confirmed his suspicion. He took a moment. He worked out the implications. He went back to tell the others.",
      ],
      advanced: [
        "She assessed the situation. She made a decision. She communicated it. She moved. The group followed.",
        "He found what he was looking for. He confirmed it twice. He brought the others. He said nothing until they had seen it themselves.",
        "She identified the error. She corrected her course. She said nothing about it. She kept moving. She did not repeat it.",
        "He managed the group's fear throughout the second night. He checked each person in turn. He kept his own concern contained. He maintained the fire. He was awake when the dawn came.",
        "She reached the high point. The route became clear. She mapped it mentally. She returned to the group. She explained it without hesitation.",
        "He heard the signal. He confirmed the direction. He alerted the others. They moved to open ground. They did everything right.",
        "She had one usable option. She took it. It worked. She noted what had made it work. She filed it away.",
        "He made the mistake on day two. He recognised it on day three. He corrected for it on day four. He told the group on day five. By then it no longer mattered.",
        "She led them to the water source. She tested it. She confirmed it was safe. She organised the refill. She set the next objective before anyone had finished drinking.",
        "He sat with the group after they were found. He said very little. He watched each of them talk to the rescuers. He felt something that took him a long time to name.",
      ],
    },

    "author-stems": {
      beginner: [
        "Without warning, the ...",
        "All of a sudden, she ...",
        "From behind the trees, ...",
        "Before she could stop herself, ...",
        "Just as he reached the top, ...",
        "For a moment, everything ...",
        "Out of nowhere, a sound ...",
        "Right at that second, she saw ...",
        "Deep in the bush, something ...",
        "At the edge of the water, ...",
      ],
      intermediate: [
        "Without warning, the silence broke and ...",
        "Deep inside, she knew that staying put was ...",
        "What none of them had expected was ...",
        "For a moment, the sound of the helicopter ...",
        "Long before the others woke, she had already ...",
        "Somewhere below, the sound of running water meant ...",
        "With the tide line closer than it had been that morning, she ...",
        "Somewhere between exhaustion and determination, she ...",
        "In the space of a single second, everything ...",
        "What she had not prepared for was the way ...",
      ],
      advanced: [
        "Somewhere between the decision to move and the moment she did, she ...",
        "What none of them had said aloud, but all of them had understood, was ...",
        "Long before the others began to lose hope, she had already ...",
        "With a steadiness she did not entirely feel, she ...",
        "Deep inside, beneath the performance of calm, she knew ...",
        "What the map could not account for was ...",
        "In the years that followed, she would return to this moment and ...",
        "Somewhere between panic and something that felt almost like clarity, she ...",
        "Without warning and without any of the drama she had imagined, ...",
        "What she had held onto, through every hour of it, was ...",
      ],
    },

    "information-adders": {
      beginner: [
        "She was cold.",
        "He found some water.",
        "The fire went out.",
        "She heard a sound.",
        "He was tired.",
        "They kept walking.",
        "She built a shelter.",
        "He called for help.",
        "The sun went down.",
        "She was scared.",
      ],
      intermediate: [
        "She reached the top of the ridge.",
        "He rationed the last of the water.",
        "The fire held through the night.",
        "She heard the helicopter pass overhead.",
        "He found a trail marker at the base of the hill.",
        "They had been walking since before dawn.",
        "She decided to stay put and wait.",
        "He built a signal on the open ground.",
        "The temperature dropped sharply after sunset.",
        "She crossed the creek at the narrowest point.",
      ],
      advanced: [
        "She made the call to move south.",
        "He kept his doubt from the rest of the group.",
        "The signal fire burned through the second night.",
        "She identified the error in their original route.",
        "He managed the group's morale through the worst of it.",
        "The terrain was more difficult than the map had suggested.",
        "She reached a decision before the others woke.",
        "He returned to the camp with nothing useful.",
        "The gap between their supplies and their needs became critical.",
        "She found what she had been looking for on the fourth day.",
      ],
    },
  },
};
