/** Theme pack: The Market — scene-based example bank (loaded before app inline script). */
globalThis.ACHIEVE_PRELOAD_THEME_BANKS = globalThis.ACHIEVE_PRELOAD_THEME_BANKS || {};
globalThis.ACHIEVE_PRELOAD_THEME_BANKS["the-market"] = {
  title: "The Market",
  bank: {
    "predictable-starts": {
      beginner: [
        "She held her mum's hand tight.",
        "He wanted the red one on the top shelf.",
        "It smelled like fish and fresh bread.",
        "They had been walking for a long time.",
        "The man behind the stall gave her a free sample.",
        "He lost sight of his dad near the fruit stalls.",
        "She had two coins left in her pocket.",
        "It was too loud for her to hear what he said.",
        "They stopped at every stall on the way through.",
        "He had never seen so many people in one place.",
      ],
      intermediate: [
        "She had been given ten dollars and told to make it last.",
        "He noticed the stall owner watching him even when serving someone else.",
        "It was busier than usual and she was not sure why.",
        "They had split up to cover more ground but now she could not find him.",
        "The price on the sign was not the price the man asked for.",
        "He counted his change twice before putting it away.",
        "She felt out of place among the Saturday morning crowd.",
        "It was the kind of place where you could find almost anything.",
        "They had been here before but never without an adult.",
        "His job was to carry the bags and not complain.",
      ],
      advanced: [
        "She had not come to buy anything.",
        "He understood, watching the exchange, that money was only part of what was changing hands.",
        "It was the oldest market in the city and it had outlasted everything built around it.",
        "They had been followed since the second stall.",
        "The transaction was completed without eye contact, which was how she preferred it.",
        "He had sold things here he was not proud of, in years he did not talk about.",
        "She recognised the woman across the crowd from a photograph she was not supposed to have seen.",
        "It was the kind of place that remembered nothing and forgot no one.",
        "They separated at the entrance because arriving together would have been a mistake.",
        "His instinct was to leave, but leaving too quickly was its own kind of signal.",
      ],
    },
    "weak-be": {
      beginner: [
    "Under the striped awning, bright colours were filling the stall.",
    "Before the shopping began, Mia was already hungry.",
    "Beside the counter, Leo was too short to see the fruit.",
    "Around the fountain, the market was busier than ever.",
    "Between the stalls, the children weren't sure which way to go.",
    "Inside the basket, the bread was still warm.",
    "Near the spice cart, Ava was holding a coin in each hand.",
    "By the fish stall, Noah was standing beside the wrong person.",
    "Against her hip, the bag was heavier than expected.",
    "After the long search, the group was glad to find a seat."
  ],

  intermediate: [
    "Near the entrance, the crowd was thicker than anywhere else.",
    "Between the baskets, Mia was certain she had seen him before.",
    "Around the market, Leo had become known for finding the best stalls.",
    "By the fruit cart, the prices were higher than her mother had warned.",
    "Behind the counter, no one was clearly in charge.",
    "Among the crowd, they were the only ones studying the strange stall properly.",
    "Behind her shoulder, someone was standing too close.",
    "Across the ice, the fish had already begun to melt.",
    "Inside his palm, the change he'd been given didn't seem correct.",
    "By midday, the whole place had become louder and more crowded."
  ],

  advanced: [
    "At the end stall, the woman wasn't there to sell anything.",
    "Among the traders, Elias was remembered by everyone and known by no one.",
    "Behind the simple arrangement, something had been hidden too carefully.",
    "Before they arrived, someone had already been watching the stall.",
    "Within seconds, the transaction had ended before she fully understood it.",
    "Across the market, Elias was careful about which stalls he visited first.",
    "Across the aisle, the man wasn't quite who he appeared to be.",
    "Behind the painted signs, the prices were meaningless and the real cost was paid elsewhere.",
    "Despite the cheerful noise, the group was running out of time.",
    "Beneath the colour and chatter, the market was a place where even silence could be bought.",
      ],
    },
    "basic-verbs": {
      beginner: [
        "She went to the stall with the big umbrella.",
        "He got an orange from the fruit stand.",
        "She looked at all the things laid out on the table.",
        "He ran to catch up with his dad.",
        "She took a sample from the lady at the end.",
        "He said he wanted the blue one.",
        "She went past the flower stall twice.",
        "He looked at the price and walked away.",
        "She got her mum to carry the heavy bag.",
        "He saw a dog sleeping under one of the stalls.",
      ],
      intermediate: [
        "She walked through every aisle before deciding what to buy.",
        "He took the last one before the woman beside him could reach it.",
        "She looked at the stall owner and said the price was too high.",
        "He went back to the same stall three times without buying anything.",
        "She got talking to the man who sold second-hand books.",
        "He said nothing but took the change and walked away quickly.",
        "She saw him make the exchange from across the aisle.",
        "He walked the full length before he found what he came for.",
        "She took the bag without checking what was inside.",
        "He looked around once and then went through the door at the back.",
      ],
      advanced: [
        "She walked past the stall without slowing, which was the signal they had agreed on.",
        "He took his time, which was how she knew something had changed.",
        "She looked at the woman across the crowd and said nothing, which said everything.",
        "He went through the motions of browsing while watching the entrance.",
        "She took the envelope from beneath the cloth without breaking her stride.",
        "He said the price was fair, which meant it wasn't.",
        "She walked away before he could see her face.",
        "He saw the whole thing from three stalls away and understood immediately what it meant.",
        "She went back the following week and the stall was gone.",
        "He got what he came for, though not in the way he had planned.",
      ],
    },
    repetition: {
      beginner: [
        "She liked the stall. The stall had bright colours. The stall was her favourite stall.",
        "He wanted to buy something. He did not have enough to buy it. He kept looking at what he wanted to buy.",
        "The bread smelled good. She wanted some bread. She asked for a piece of bread.",
        "He found his dad. His dad was at the end stall. He had been looking for his dad all morning.",
        "She counted her coins. She had three coins. Three coins were not enough.",
        "The crowd was big. She did not like the big crowd. The crowd moved very slowly.",
        "He dropped his bag. The bag fell open. He picked up the bag and kept walking.",
        "She tasted the sample. The sample was sweet. She wanted more than one sample.",
        "The stall owner smiled. She smiled back at the stall owner. The stall owner gave her something for free.",
        "He waited at the stall. The stall was busy. He kept waiting at the stall.",
      ],
      intermediate: [
        "She had been watching the same stall all morning. The stall had not had many customers. The customers who did stop at the stall did not stay long.",
        "He paid more than he should have. He knew he had paid too much. The price he paid told him something about the seller.",
        "The crowd moved in one direction. She moved against the crowd. Moving against the crowd made her easier to see.",
        "She recognised the bag. The bag had been described to her. The description of the bag had been accurate.",
        "He visited every stall. Not every stall had what he needed. He kept visiting each stall until he found the right one.",
        "The price changed when she asked again. She had written down the first price. The price she was charged was not the price she had written.",
        "She bought the last bunch. The last bunch was not as fresh as the others. She took the last bunch anyway.",
        "He watched the entrance. Two people came through the entrance together. They left the entrance separately.",
        "The smell reminded her of something. She could not say what the smell reminded her of. Whatever the smell reminded her of felt important.",
        "She made her way to the back row. The back row was quieter. At the back row she found what she had been looking for.",
      ],
      advanced: [
        "The exchange was brief. Brief exchanges in this part of the market were never accidental. Nothing accidental happened in a place where every exchange was watched.",
        "She had come for information. The information had a price. She had not expected the price of the information to be another piece of information.",
        "He knew the stall from a previous visit. The previous visit had not ended well. He had returned despite how the previous visit had ended.",
        "The crowd was cover. She used the crowd deliberately. Deliberately using the crowd was something she had been taught.",
        "He recognised the signal. The signal had been agreed on weeks earlier. Weeks earlier, when they agreed on the signal, he had not believed it would be necessary.",
        "She found the address on a scrap of paper tucked beneath a cloth. The cloth covered other scraps of paper. None of the other scraps of paper had an address.",
        "He paid in cash. Cash left no record. A place with no record was a place where cash was the only currency that mattered.",
        "The transaction was clean. Clean transactions were rare here. She had been told to expect a clean transaction and had not believed it.",
        "She watched him leave. Leaving was the easy part. The part after leaving was what she had not planned for.",
        "He came back the following week. The following week, the stall was in a different position. A stall in a different position meant the arrangement had changed.",
      ],
    },
    "weak-adjectives": {
      beginner: [
        "She found a pretty flower at the first stall.",
        "He carried a heavy bag through the crowd.",
        "The old man behind the counter smiled at her.",
        "She bought a small bunch of grapes.",
        "It was a busy morning and the aisles were full.",
        "He had a good look at everything before choosing.",
        "She found a nice ribbon at the fabric stall.",
        "The cold drink felt good in the heat.",
        "He helped the old lady carry her shopping.",
        "She had a long wait at the popular stall.",
      ],
      intermediate: [
        "The old woman at the far end sold things nobody else stocked.",
        "She kept her money in a small pouch inside her jacket.",
        "The dark corner of the market was where the cheaper stalls were.",
        "He was a thin man with a quiet way of watching people.",
        "The heavy crates were stacked against the back wall.",
        "She had a strange feeling she could not shake all morning.",
        "It was a long, busy morning and she was glad when it ended.",
        "The cold storage at the back kept the better produce fresh.",
        "He stood in the quiet section where the old furniture was sold.",
        "She had a difficult time choosing between the two.",
      ],
      advanced: [
        "The old quarter was where the serious business happened.",
        "She moved through the busy section quickly and found a quiet corner to wait.",
        "He was a thin, calm man who never seemed to be in a hurry.",
        "The strange arrangement of the stalls made it hard to track anyone for long.",
        "She had come prepared for a difficult conversation.",
        "The dark doorway at the back led somewhere she had not been before.",
        "He carried a heavy case and asked no help from anyone.",
        "The emotional weight of the place was hard to explain to someone who had not grown up here.",
        "The cold morning made the hot food stalls the busiest in the building.",
        "It was a long and difficult search through a small, crowded space.",
      ],
    },
    adverbs: {
      beginner: [
        "She carefully counted out her coins.",
        "He quickly grabbed the last apple.",
        "She quietly tugged on her mum's sleeve.",
        "The stall owner smiled very kindly at her.",
        "He slowly made his way through the crowd.",
        "She really wanted the one on the top shelf.",
        "He politely asked how much it cost.",
        "The bag was too heavy for her to carry alone.",
        "She happily ate the free sample.",
        "He carefully put the change back in his pocket.",
      ],
      intermediate: [
        "She carefully watched the stall owner count the change.",
        "He moved quickly through the crowd without looking back.",
        "She quietly told him the price was higher than expected.",
        "He had clearly been here before, the way he moved through the place.",
        "She reluctantly handed over the last of her money.",
        "He spoke very quietly to the woman behind the counter.",
        "She was absolutely certain she had seen him somewhere before.",
        "He carefully placed the package in his bag without drawing attention.",
        "She walked briskly to the far end where the crowd was thinner.",
        "He waited patiently while the transaction ahead of him finished.",
      ],
      advanced: [
        "She moved deliberately through the crowd, stopping only where it looked natural to stop.",
        "He had quietly built a reputation here over many years.",
        "She spoke very calmly to the woman, which was harder than it looked.",
        "He watched carefully as the second man counted the money twice.",
        "She had clearly underestimated how long the whole thing would take.",
        "He smiled broadly and said absolutely nothing of use.",
        "She placed the item very precisely where she had been told to leave it.",
        "He left quickly, but not so quickly that anyone would notice.",
        "She had always known, instinctively, that this was where it would happen.",
        "He spoke softly and kept his eyes carefully away from the entrance.",
      ],
    },
    "stop-words": {
      beginner: [
        "She went to the stall and she got an apple and she paid for it and she ate it.",
        "He had some money and he went to the stall and he looked at the things and he could not decide.",
        "It was a big place and there were lots of people and it was very loud.",
        "She saw the bag and she liked it and she asked how much it was.",
        "He went with his mum and they walked around and they looked at lots of things.",
        "There was a stall with flowers and she stopped and she looked at them and she smelled them.",
        "He had a look at the things on the table and then he picked one up and then he put it back.",
        "She was hungry and so she got a snack and then she felt a bit better.",
        "It was hot and there were lots of people and she was tired and she wanted to go home.",
        "He found his mum and she had bags and so he helped her carry them.",
      ],
      intermediate: [
        "She had been walking around for a while and she had looked at a lot of things and she had not bought anything yet.",
        "There was a stall that had things she had not seen before and she stopped and had a look and the man told her the price and it was too much.",
        "He went to the place where they usually met and he waited and she did not come and so he waited a bit longer.",
        "It was the kind of place where there were all sorts of people and all sorts of things and you never really knew what you would find.",
        "She had the money in her pocket and she knew what she wanted and she went to the stall and then it was sold out.",
        "He looked at the stall and he looked at the price and he thought about it and then he decided it was not worth it.",
        "There was a lot of noise and a lot of people and she found it hard to concentrate on what she was looking for.",
        "She got talking to the woman at the end stall and it turned out they were from the same place and they talked for a while.",
        "He took his time and he went through every aisle and he had a look at everything before he decided what to do.",
        "Then she found what she was looking for and then she paid for it and then she put it in her bag and then she left.",
      ],
      advanced: [
        "It was the kind of place that had a lot of history to it and there was a feeling that things happened there that did not happen anywhere else and that was the point of it.",
        "She was not sure that the arrangement she had been told about was the kind of arrangement that was going to work out in the way that she had been led to believe.",
        "He had been coming to this place for a number of years and in that time he had seen a lot of things that he had chosen not to get involved in and this was not going to be any different.",
        "There was something about the way the transaction had been described to her that made her feel like there was more to it than she had been told and she was not sure she wanted to find out what that was.",
        "She went to the part with the older stalls and she had a look around and she did not see what she was looking for and so she tried another section.",
        "It was clear to her that the person she was supposed to meet was not going to be there and that the fact that he was not there was itself a kind of message.",
        "He had a system and the system involved going to certain stalls in a certain order and not making it obvious that he was going to certain stalls in a certain order.",
        "There were a lot of people around and that was good because a lot of people meant that no one was paying attention to any one person in particular and that was the whole idea.",
        "She was not in a position to say what the thing she had seen actually meant but she knew that it meant something and that the something it meant was not good.",
        "He went through the whole place once just to get a sense of it and then he went through it again more slowly and the second time he noticed things he had missed the first time.",
      ],
    },
    "filter-words": {
      beginner: [
        "She heard someone calling her name in the crowd.",
        "He noticed the bag of cherries was cheaper than the others.",
        "She felt a hand on her shoulder and turned around.",
        "He saw his dad waving from the end of the aisle.",
        "She noticed the stall owner was watching her.",
        "He felt the coins in his pocket to check they were still there.",
        "She heard the bell that meant it was closing time.",
        "He thought the fish smelled a bit off.",
        "She noticed her mum had stopped at a different stall.",
        "He felt a little lost among all the people.",
      ],
      intermediate: [
        "She noticed the same man had passed the stall three times.",
        "He felt certain he had been given the wrong change.",
        "She heard two people arguing quietly behind the fabric stall.",
        "He realised the person he was looking for had already left.",
        "She sensed that the stall owner did not want her to stay too long.",
        "He watched the exchange from behind a rack of second-hand jackets.",
        "She thought she recognised the voice but could not place the face.",
        "He knew something had happened before he could say what it was.",
        "She wondered why the last stall on the row was always empty.",
        "He noticed the price had been changed after she asked about it.",
      ],
      advanced: [
        "She sensed, without looking directly, that she was being followed.",
        "He realised the meeting had already taken place by the time he arrived.",
        "She observed that the two men had not spoken but had understood each other perfectly.",
        "He felt the shift in the crowd before he could explain what had caused it.",
        "She noticed the stall had no prices displayed, which she understood to mean it was not for everyone.",
        "He knew the man's face from somewhere he could not immediately place.",
        "She feared the window she had been given had already closed.",
        "He watched the whole transaction from across the aisle and understood it was not the first time that morning.",
        "She remembered this part of the place from childhood, and the memory made her cautious.",
        "He sensed that the woman he had come to meet already knew why he was there.",
      ],
    },
    "sentence-structure": {
      beginner: [
        "She went in. It was busy. She stayed close to her mum.",
        "He found the stall. He looked at the prices. He did not have enough.",
        "The bag was heavy. She carried it. Her arm got sore.",
        "She tried the sample. It was good. She wanted to buy some.",
        "He got lost. He looked around. He found his dad.",
        "The stall had flowers. They were pretty. She stopped to look.",
        "She bought an apple. It was red. She ate it on the way home.",
        "He had five dollars. He looked around. He spent it all.",
        "The crowd was big. She held her mum's hand. They walked slowly.",
        "He saw a dog. It was under a stall. It looked friendly.",
      ],
      intermediate: [
        "She found the stall. The price was high. She bought it anyway.",
        "He had a list. He worked through it. He missed one thing.",
        "The place was crowded. She moved carefully. She kept her bag close.",
        "He noticed the man. The man watched him. He walked on.",
        "She reached the last row. The stall she wanted was gone. She looked around.",
        "He checked his money. It was enough. He made his choice.",
        "The queue was long. She waited. She got to the front eventually.",
        "He tried the sample. It was not what he expected. He bought it anyway.",
        "She turned the corner. There was a stall she had not seen before. She stopped.",
        "He handed over the money. The woman counted it. She handed some back.",
      ],
      advanced: [
        "She arrived early. The serious buyers were already there. She had not expected that.",
        "He found the stall. It was not what had been described. He stayed anyway.",
        "The crowd was useful cover. She used it. Someone else had the same idea.",
        "She made the exchange. It was over quickly. She did not look back.",
        "He had been here before. Things were different now. He was not sure how.",
        "She found the address. It matched the one she had been given. That should have been reassuring.",
        "He waited for twenty minutes. Nobody came. He gave it another five.",
        "The stall was exactly where she had been told. That made her more nervous, not less.",
        "She left without buying anything. That was the arrangement. She hoped he had understood it.",
        "He recognised the signal. He had three minutes. He moved.",
      ],
    },
    "literary-devices": {
      beginner: [
        "The market was noisy and full of people.",
        "She walked past the stalls and looked at the things on them.",
        "The food smelled nice when she walked past.",
        "He carried the bags for his mum.",
        "There were lots of colours at the flower stall.",
        "She waited while her mum paid for things.",
        "The crowd moved slowly through the aisles.",
        "He found the stall he was looking for at the end of the row.",
        "The fruit was in neat piles on the table.",
        "She bought something and put it in her bag.",
      ],
      intermediate: [
        "The place was crowded and hard to move through.",
        "She stopped at the stall because something caught her attention.",
        "The noise made it hard to hear what the stall owner was saying.",
        "He walked past the old section where the prices were lower.",
        "The smell of food was strong near the middle.",
        "She looked at the display for a while before moving on.",
        "The light inside was dim and made everything harder to see.",
        "He reached the far end and turned back.",
        "The stall was run by a man who had been there for years.",
        "She left with more than she had intended to buy.",
      ],
      advanced: [
        "It opened at dawn and by midday the energy had changed completely.",
        "She moved through the crowd with a purpose that was not obvious to anyone watching.",
        "The older section had a different atmosphere to the rest.",
        "He conducted the transaction as he conducted most things — without expression.",
        "The noise and movement made it easy to go unnoticed.",
        "She had been coming here for years and the place had changed around her.",
        "The stall at the far end operated differently to the others.",
        "He left with something he had not planned to leave with.",
        "The crowd thinned as the afternoon went on and the stalls began to close.",
        "She understood the place in a way that took years to acquire.",
      ],
    },
    "paragraph-cohesion": {
      beginner: [
        "She found the stall. It was sunny. The lady smiled. She had a hat on. She bought some grapes.",
        "He had money in his pocket. The dog was barking nearby. He wanted the blue one. His shoes were new. He did not spend all of it.",
        "It was busy. She liked strawberries. Her bag was purple. There were lots of stalls. She got tired.",
        "He walked around. There was a man with a big hat. He bought some bread. It was Tuesday. The bread was warm.",
        "She stopped at the flower stall. Her mum was somewhere else. The flowers were yellow. She had two dollars left. She walked on.",
        "He lost his mum. The place was noisy. He stood still. A dog ran past. His mum found him.",
        "She tried a sample. It tasted good. There was music playing. She bought one. Her bag was getting heavy.",
        "He watched the man pack the bags. It was getting hot. He wanted a cold drink. The bags were full. They started walking home.",
        "The stall had nice things in it. She had homework due. She looked at everything. It smelled like cheese. She bought some.",
        "He gave the lady his money. The sky was cloudy. She gave him something back. He was hungry. He put it in his bag.",
      ],
      intermediate: [
        "She had been given a list. The stall she needed was not where she expected. Her friend had texted her twice. She worked through it anyway. The last item was sold out.",
        "He arrived before it got busy. The fish stall had the best prices early. He had slept badly. He got what he came for. He was home before nine.",
        "She saw someone she recognised. The crowd was thick near the entrance. She had not seen him in years. She was looking for olive oil. She did not stop to speak to him.",
        "He had exactly enough money. His phone battery was low. The prices had gone up since last time. He made it work. He walked home a different way.",
        "The stall was in the back row. She had read about it online. Her bag was already full. It was run by two sisters. She bought something she did not need.",
        "He counted his change twice. It was raining lightly outside. The woman behind the counter did not notice. He said nothing about it. He went back the following week.",
        "She had been looking for this for months. The stall owner did not speak much English. It was almost noon. They worked it out between them. She paid more than the sign said.",
        "He stopped for coffee at the side entrance. A man sat down at the same table. They had not arranged to meet. He finished his coffee quickly. He did not look up again.",
        "She bought the last one on the table. Her feet were sore. Someone asked if she had seen another stall like it. It was getting loud near the centre. She said she had not.",
        "He was there for ten minutes. The purpose of his visit was unclear to anyone watching. He bought a newspaper. He stopped at one stall only. He did not return that day.",
      ],
      advanced: [
        "The package had been left at the agreed stall. She arrived six minutes late. The stall owner was someone she had not met before. The package was gone. She bought a bunch of herbs and left.",
        "He had a description of the person he was looking for. The crowd was busier than he expected. After an hour he was no longer sure the description was accurate. He stayed another hour. He did not find the person.",
        "She came every week. In three months she had learned the rhythms of the place. She knew which stalls were fronts. She knew which owners asked no questions. She had not yet decided what to do with that knowledge.",
        "The meeting had been arranged weeks in advance. He arrived to find the stall replaced by a different one. The new owner was friendly and unhelpful. He bought something he did not need to justify standing there. He left without making contact.",
        "She had been told the exchange would be simple. Simple was not how she would have described it. The first handoff went smoothly. The second did not happen at all. She was still waiting for an explanation three days later.",
        "He watched the same woman pass three stalls without buying anything. She stopped at the fourth. She did not buy anything there either. He looked away for a moment. When he looked back she was gone.",
        "The place had been her grandmother's domain. Every stall had a memory attached to it. Coming back alone felt different to how she had imagined it would. She bought the same things her grandmother always bought. She drove home without stopping.",
        "She located the stall in less than a minute. She had studied the layout in advance. The item was priced higher than she expected. She did not negotiate. She paid and moved on before anyone could observe the transaction.",
        "He had worked this beat for eleven years. In that time three people had tried to use him. Two of them he had reported. The third he had helped, for reasons he had never fully explained to himself. He was thinking about the third one today.",
        "The information was in the package. The package was at the stall. The stall was gone. She stood in the empty space and considered what that meant for everything that was supposed to happen next.",
      ],
    },
    "narrative-types": {
      beginner: [
        "She walked in. She looked around. She found her mum. They walked to a stall.",
        "He picked up the apple. He looked at it. He put it back. He walked on.",
        "She found the stall. She looked at the prices. She paid. She put it in her bag.",
        "He got lost. He looked around. He saw his dad. He ran over.",
        "She tried a sample. She liked it. She bought one. She walked away.",
        "He counted his money. He chose something. He paid for it. He left.",
        "She stopped at a stall. She looked at the things. She did not buy anything. She kept walking.",
        "He found what he wanted. He checked the price. He had enough. He bought it.",
        "She waited in the queue. She got to the front. She ordered. She stepped aside.",
        "He carried the bag. He followed his mum. She paid. They went home.",
      ],
      intermediate: [
        "She found the stall she was looking for. She asked the price. She paid. She left.",
        "He walked to the back row. He checked the stalls. He found the one he wanted. He made his purchase.",
        "She counted her money. She worked out what she could afford. She made a choice. She walked to the stall.",
        "He reached the entrance. He looked around. He spotted the stall. He went over.",
        "She joined the queue. She waited. She got to the front. She asked for what she needed.",
        "He checked the price. He checked his money. He had enough. He bought it.",
        "She found the stall closed. She looked for an alternative. She found one. She bought from there instead.",
        "He negotiated the price. The stall owner agreed. He paid. He put it in his bag and left.",
        "She walked the full length. She found nothing she needed. She turned around. She tried again.",
        "He arrived at the meeting point. He waited. The person came. They spoke briefly. He left.",
      ],
      advanced: [
        "She arrived at the arranged time. The contact was not there. She waited ten minutes. She left.",
        "He identified the stall from the description he had been given. He approached. He made the purchase. He walked away.",
        "She moved through the crowd to the back section. She found the stall. She examined the item. She left without buying.",
        "He waited at the corner until he saw the signal. He crossed the space. He made the exchange. He left by the side entrance.",
        "She located the package beneath the table. She took it. She replaced it with the envelope. She moved on.",
        "He arrived early and walked the space. He identified the exits. He found a position with clear sightlines. He waited.",
        "She spoke to the stall owner. She asked about the item. She was told it was not available. She thanked him and left.",
        "He followed the route he had been given. He made the three stops in order. He completed the last one. He sent the message.",
        "She returned the following week. The contact was there this time. They exchanged what had been agreed. She went home.",
        "He found what he had come for at the last stall. He completed the transaction. He did not look back. He was gone before the crowd thinned.",
      ],
    },
    "author-stems": {
      beginner: [
        "Without warning, she heard ...",
        "All of a sudden, he saw ...",
        "From across the crowd, ...",
        "Before she could stop herself, she picked up ...",
        "Just as he reached the stall, ...",
        "For a moment, the crowd ...",
        "Out of nowhere, a voice ...",
        "Right at that second, she noticed ...",
        "Deep in the market, something ...",
        "At the very last stall, he found ...",
      ],
      intermediate: [
        "Without warning, the crowd shifted and ...",
        "Deep inside, she knew the man at the stall was ...",
        "What nobody had noticed was the moment when ...",
        "For a moment, the whole place seemed to ...",
        "Long before she reached the back row, she had already ...",
        "Behind the last stall, something ...",
        "Between two stalls arguing over prices she could not follow, she reached for ...",
        "Somewhere between the entrance and the far end, she realised ...",
        "In the space of a single second, everything around her ...",
        "What she had not prepared for was the way he looked at her when ...",
      ],
      advanced: [
        "Somewhere between arriving and leaving, she understood that ...",
        "What nobody in that crowded place was willing to acknowledge was that ...",
        "Long before the stalls opened, he had already positioned himself to ...",
        "With a calmness she did not feel, she completed the transaction and ...",
        "Deep inside, beneath the noise and movement of the place, she sensed that ...",
        "What the arrangement could not account for was the moment when ...",
        "In the years that followed, she would return to that morning and wonder whether ...",
        "Somewhere between the version of events she gave later and what had actually happened, the truth ...",
        "Without any outward sign that something had changed, she ...",
        "What she had spent months preparing for turned out to be ...",
      ],
    },
    "information-adders": {
      beginner: [
        "She bought an apple.",
        "He lost his mum.",
        "The stall was busy.",
        "She tried the sample.",
        "He carried the bags.",
        "The crowd moved slowly.",
        "She spent all her money.",
        "He found what he wanted.",
        "The bread smelled good.",
        "She waited in the queue.",
      ],
      intermediate: [
        "She found the stall at the back row.",
        "He noticed the price had changed.",
        "The woman behind the counter watched him carefully.",
        "She returned the following week.",
        "He counted his change before leaving.",
        "The last stall on the row was always the busiest.",
        "She bought more than she had planned to.",
        "He reached the meeting point a few minutes late.",
        "The stall was not where she remembered it.",
        "She left without speaking to anyone.",
      ],
      advanced: [
        "She completed the transaction without drawing attention.",
        "He arrived to find the stall had moved.",
        "The contact was not where he had expected.",
        "She left the package at the agreed point.",
        "He had been watching the entrance for forty minutes.",
        "The exchange took less than thirty seconds.",
        "She recognised the stall owner from a previous visit.",
        "He sent the message before he had left the building.",
        "The meeting did not go as either of them had planned.",
        "She walked away with more information than she had arrived with.",
      ],
    },
  },
};
