/** Theme pack: The Deep — pressure, darkness, below; title not hammered as a repeated noun. */
globalThis.ACHIEVE_PRELOAD_THEME_BANKS = globalThis.ACHIEVE_PRELOAD_THEME_BANKS || {};
globalThis.ACHIEVE_PRELOAD_THEME_BANKS["the-deep"] = {
  title: "The Deep",
  bank: {
    "predictable-starts": {
      beginner: [
        "He swam down too far.",
        "She could not see the bottom.",
        "It was very dark under the water.",
        "They stayed close to the boat.",
        "The water was cold and dark.",
        "He could not touch the sand.",
        "She held her breath for a long time.",
        "It was quiet under the waves.",
        "They saw something move below them.",
        "He was scared to look down.",
      ],
      intermediate: [
        "He swam deeper than he was supposed to.",
        "She pressed her face to the glass and looked down.",
        "It moved slowly through the dark water below them.",
        "They had never seen anything like it before.",
        "The shadow passed under the boat without making a sound.",
        "He kicked hard but the surface felt far away.",
        "She could not see where the bottom was.",
        "It felt colder the further down she went.",
        "They stayed together as the water darkened around them.",
        "He reached out but there was nothing to hold onto.",
      ],
      advanced: [
        "He had never been this far from the surface before.",
        "She understood, for the first time, how small she was.",
        "It rose from the darkness without any sound or warning.",
        "They had agreed not to go past the drop-off, but nobody turned back.",
        "The light from above grew thin and then disappeared entirely.",
        "He could feel the pressure building as he went deeper.",
        "She watched the last of the light fade and kept swimming.",
        "It had been down there long before any of them arrived.",
        "They moved in silence through water that seemed to have no floor.",
        "He reached the point where the reef ended and the dark began.",
      ],
    },

    "weak-be": {
    "Below the boat, Liam swam too deep.",
    "Through the mask, Mia couldn't see the bottom.",
    "Under the water, the world was dark.",
    "Beside the boat, the children stayed close.",
    "Around his legs, the water was cold and black.",
    "Far below the surface, Noah couldn't touch the sand.",
    "Before rising, Ava held her breath too long.",
    "Beneath the waves, the ocean was silent.",
    "Below their feet, something was moving.",
    "Near the reef edge, Kai was scared to look down."
  ],

  intermediate: [
    "Beyond the reef, Liam had swum deeper than he should have.",
    "Against the glass, Mia pressed her face and looked down.",
    "Through the dark water, something was moving beneath them.",
    "Until that moment, none of them had seen anything like it.",
    "Under the boat, a shadow passed without a sound.",
    "Toward the surface, Noah kicked hard but barely moved.",
    "Below her fins, Ava couldn't see where the bottom was.",
    "With every metre, the water was growing colder.",
    "As the light faded, the group stayed close together.",
    "Beside the rock wall, Kai reached out but found nothing."
  ],

  advanced: [
    "Below the thinning light, Liam had never felt so far from the surface.",
    "For the first time, Mia understood how small she was.",
    "From the darkness, something rose without warning.",
    "Past the drop-off, nobody was willing to turn back.",
    "Above them, the last thread of light had disappeared.",
    "With each metre, the pressure was building around Noah’s chest.",
    "Through the fading blue, Ava kept swimming downward.",
    "Long before their boat arrived, something had been waiting below.",
    "Between the cliffs of coral, the divers moved through water with no visible floor.",
    "At the reef’s edge, Kai reached the place where the dark began.",
      ],
    },

    "basic-verbs": {
      beginner: [
        "She went into the water slowly.",
        "He saw something big below him.",
        "She looked down into the dark.",
        "He got to the edge and stopped.",
        "They went in together.",
        "She said it was too deep.",
        "He made a splash when he jumped.",
        "She took a big breath and went under.",
        "He ran to the edge of the pool.",
        "They saw a shadow in the water.",
      ],
      intermediate: [
        "She went to the edge and looked down into the dark water.",
        "He saw something move below the surface and stopped swimming.",
        "They got back in the boat when the water turned cold.",
        "She said nothing but looked at the dark shape below her.",
        "He went deeper than the others and saw something strange.",
        "She took one look at the drop-off and said she was not going in.",
        "He made his way to the surface as fast as he could.",
        "They saw the shape again and went back to shore.",
        "She got to the rope and held on.",
        "He ran to the rocks and looked out over the dark water.",
      ],
      advanced: [
        "She went to the edge of the reef and looked into the drop-off below.",
        "He saw the shape clearly for the first time and said nothing to the others.",
        "She took the torch and went into the underwater passage without waiting.",
        "He made a note of the depth on his wrist slate and went deeper still.",
        "She said the shape was too large to be anything she recognised.",
        "They got to the bottom and saw that the wreck was not where the charts said.",
        "He went back to the surface with nothing but a question he could not answer.",
        "She looked at the sonar reading and said the number out loud.",
        "He ran his light along the seafloor and saw the outline of something enormous.",
        "She took the sample, looked at it once, and went back up.",
      ],
    },

    "repetition": {
      beginner: [
        "The dark water was cold. The cold water was deep. The deep cold water scared her.",
        "He swam down. He swam further down. He swam until the water was black.",
        "She saw a fish. The fish was big. The big fish swam past her.",
        "The water was cold. The cold made her stop. She stopped because of the cold water.",
        "She heard a sound. The sound was low. The low sound scared her.",
        "He held his breath. His breath ran out. He could not hold his breath any longer.",
        "She looked down into the dark. The dark was deep. Looking into the deep dark scared her.",
        "The water pulled him down. He felt the pull. The pulling water dragged him down.",
        "The creature swam up. It swam up slowly. It swam slowly up toward her.",
        "He went to the edge. The edge was slippery. He slipped on the slippery edge.",
      ],
      intermediate: [
        "She swam toward the light. The light was far below. The further she swam, the dimmer the light became.",
        "He heard a sound in the water. The sound was deep. The deep sound echoed through the water around him.",
        "The creature moved through the dark. The dark water hid the creature. She could not see the creature moving through the dark.",
        "She held her breath as she dived. The dive took her deep. She could not hold her breath for the whole dive.",
        "He reached the bottom of the pool. The bottom was dark. He did not stay at the dark bottom for long.",
        "The water was cold at the surface. The cold grew worse as she dived. By the time she reached the bottom the cold was all she could feel.",
        "She saw a shadow below her. The shadow was large. The large shadow moved slowly beneath her.",
        "He swam toward the cave. The cave was dark inside. He stopped at the entrance of the dark cave.",
        "The rope led down into the water. The water swallowed the rope. She followed the rope into the water below.",
        "She heard the sound again. The sound came from below. Below her, the sound grew louder.",
      ],
      advanced: [
        "He had dived deep before, but this dive felt different. The difference was something he could not name. Something about this particular dive was wrong.",
        "She followed the shape through the dark water. The dark pressed in from every side. The shape moved through it as though the dark were familiar.",
        "The silence at the bottom was different from any silence above. Above the surface, silence was an absence of sound. Here, the silence felt like a presence.",
        "She measured the depth and measured it again. Each measurement gave the same result. The result was deeper than the charts said was possible.",
        "The creature rose from below. Below it, there was nothing but darkness. She could not see what lay below the creature in that darkness.",
        "He felt the current change as he went deeper. The deeper he went, the stronger the current became. The current at this depth was not on any chart.",
        "She photographed the formation on the seafloor. The formation appeared in none of her reference materials. No reference she had could account for a formation like this.",
        "The pressure increased with every metre. Each metre felt like the last he could manage. He had managed thirty metres before, but this felt different.",
        "He reached the wreck and found the door. The door had not been opened from inside. Finding a door that had never been opened told him what he needed to know.",
        "She descended past the reef into darkness. The darkness was not empty. Whatever filled the darkness was not something she had prepared for.",
      ],
    },

    "weak-adjectives": {
      beginner: [
        "The water was cold and dark.",
        "She found a big shell on the bottom.",
        "It was a strange fish she had never seen.",
        "The cave was dark and empty inside.",
        "He saw a small light far below.",
        "The water felt heavy on her chest.",
        "It was a long way to the surface.",
        "She saw something big move past.",
        "The old boat had sunk to the bottom.",
        "He found a small rock on the sand.",
      ],
      intermediate: [
        "The dark water hid something strange beneath the surface.",
        "She swam past a big rock covered in old coral.",
        "The empty cave at the bottom was cold and quiet.",
        "He saw a long dark shape pass slowly below him.",
        "The strange sound came from deep in the cold water.",
        "She found a small old anchor half buried in the sand.",
        "The heavy feeling in her chest made her swim back up.",
        "He looked into the dark hole and saw something move.",
        "The cold empty water stretched in every direction below her.",
        "She reached the big reef and saw how old and broken it was.",
      ],
      advanced: [
        "The dark cold water at this depth was difficult to move through.",
        "She found a strange object half buried in the empty seafloor.",
        "The heavy pressure made every movement difficult and slow.",
        "He entered the old wreck through a small opening near the bow.",
        "The long corridor inside the hull was dark and completely empty.",
        "She felt a powerful and strange pull from the cold water below her.",
        "The big shadow that passed beneath them left a tense difficult silence.",
        "He pulled the heavy door open and found the room on the other side empty.",
        "The old dark structure on the seafloor was difficult to identify from above.",
        "She noticed the strange cold current that ran along the bottom of the cave.",
      ],
    },

    "adverbs": {
      beginner: [
        "She swam very slowly to the bottom.",
        "He looked down very carefully.",
        "She held her breath very tightly.",
        "The fish swam quietly past her.",
        "He suddenly saw something move.",
        "She quickly swam back up.",
        "It moved very slowly in the dark.",
        "He quietly slipped under the water.",
        "She breathed very slowly and waited.",
        "He swam really fast to the surface.",
      ],
      intermediate: [
        "She swam very carefully toward the dark shape below her.",
        "He suddenly noticed the water was getting colder.",
        "She breathed very slowly to make her air last longer.",
        "He moved very quietly through the water so as not to disturb anything.",
        "She suddenly realised how far down she had come.",
        "He looked very carefully at the shape on the seafloor.",
        "She swam quickly back to the surface when she saw it move.",
        "He gently reached out toward the creature floating in front of him.",
        "She very slowly turned to look at what was behind her.",
        "He carefully and slowly followed the rope down into the dark.",
      ],
      advanced: [
        "She descended very carefully, watching the pressure gauge closely.",
        "He moved silently through the wreck, barely disturbing the silt.",
        "She suddenly understood why the others had turned back at this point.",
        "He pressed very slowly against the rusted door until it gave way.",
        "She hovered very still in the water, barely breathing.",
        "He studied the seafloor very carefully before touching anything.",
        "She rose very slowly to avoid the bends, counting each metre.",
        "He quietly noted that the creature was significantly larger than he had first thought.",
        "She very deliberately stayed close to the wall as she moved through the passage.",
        "He breathed very steadily even as the shape below him grew larger.",
      ],
    },

    "stop-words": {
      beginner: [
        "She went into the water and it was cold and she was scared.",
        "He had a look down and it was dark and he did not want to go in.",
        "The water was deep and it was cold and there was something in it.",
        "She went under and she held her breath and she looked around.",
        "He got to the edge and he looked down and it was a long way.",
        "She was in the water and it was dark and she could not see.",
        "He went down and it got darker and he came back up.",
        "She saw a fish and it was big and it went past her.",
        "He was at the bottom and it was cold and he went back up.",
        "She looked down and it was dark and she did not go in.",
      ],
      intermediate: [
        "She went to the edge of the water and she looked down and it was very dark and she was not sure she wanted to go in.",
        "He had been in the water for a while and it was getting cold and there was something down there and he was not sure what it was.",
        "There was a sound in the water and it came from below and it was low and heavy and she did not know what it was.",
        "She held her breath and she went under and she swam down and it got darker and colder the further she went.",
        "He got to the bottom and he had a look around and there was not much to see and so he went back up.",
        "There was something in the water and it was big and it moved slowly and she watched it go past her.",
        "She had always been a good swimmer but the water here was different and it made her feel like she was not in control.",
        "He went past the reef and it got darker and the water felt different and he was not sure he should keep going.",
        "There was a shape at the bottom and it was hard to see and she went closer and she wished she had not.",
        "She was in the water and she could hear sounds and they were coming from below her and she did not know what they were.",
      ],
      advanced: [
        "It was the kind of water that had a weight to it and she could feel that weight in a way that was hard to explain to someone who had not been in it.",
        "There was something about the depth of the place that made it feel like a different world and she was not sure that she was the right kind of person to be in it.",
        "He had been told that there was nothing down there and that it was not worth the time and the effort and the risk but he had not believed it and he had been right not to.",
        "She went down past the point where the light stopped and it was at that point that she understood why people did not come here and yet she kept going.",
        "There was a shape on the seafloor and it had been there for a long time and nobody had known about it and now she was the one who had found it.",
        "He had a feeling that the thing he was looking at was something that should not be there and that feeling was the kind that he had learned to pay attention to.",
        "She was moving through the water very slowly and she was being careful and she was watching everything around her and still she almost missed it.",
        "It was not the first time he had been in deep water but it was the first time it had felt like the water was looking back at him.",
        "There was a current and it was pulling her in a direction she did not want to go and it was stronger than she had expected and she had to work hard against it.",
        "She had always been told that there was nothing out there but she was down here now and she was not so sure about that any more.",
      ],
    },

    "filter-words": {
      beginner: [
        "She felt cold when she went under.",
        "He saw something big below him.",
        "She heard a sound in the water.",
        "He felt scared when it got dark.",
        "She noticed the water was cold.",
        "He felt something brush his leg.",
        "She heard something move below.",
        "He saw a shadow pass under him.",
        "She felt the water get colder.",
        "He noticed it was very quiet.",
      ],
      intermediate: [
        "She felt the cold close in around her as she swam deeper.",
        "He noticed the light disappearing the further down he went.",
        "She heard something large moving below her in the dark.",
        "He felt certain there was something beneath him in the water.",
        "She saw the shape before the others did and said nothing.",
        "He noticed the water had changed colour at this depth.",
        "She felt the pressure building in her ears as she descended.",
        "He heard a low sound that seemed to come from everywhere at once.",
        "She realised she was much deeper than she had intended to go.",
        "He watched the shadow pass slowly beneath the hull of the boat.",
      ],
      advanced: [
        "She sensed the shift in the water before she saw what caused it.",
        "He realised he had gone past the point where turning back felt safe.",
        "She noticed the silence had taken on a different quality at this depth.",
        "He felt the current change beneath him and understood what it meant.",
        "She heard the sound again and this time she knew it was not the hull.",
        "He observed that the formation on the seafloor did not match any natural process he recognised.",
        "She felt something she could only describe as being watched, though nothing was visible.",
        "He knew the shape below him was too large to be anything he had prepared for.",
        "She wondered whether the others had felt this same thing and simply not mentioned it.",
        "He remembered a briefing note about this location that he now wished he had read more carefully.",
      ],
    },

    "sentence-structure": {
      beginner: [
        "She went in. It was dark. She came back up.",
        "He looked down. It was deep. He was scared.",
        "The water was cold. She swam anyway. She went deep.",
        "He saw something. It was big. He swam away fast.",
        "She held her breath. She went under. She looked around.",
        "He touched the bottom. It was sandy. He came back up.",
        "The fish swam past. It was strange. She watched it go.",
        "He grabbed the rope. He held on. He went down.",
        "She opened her eyes. The water was dark. She closed them.",
        "He found a shell. It was on the sand. He picked it up.",
      ],
      intermediate: [
        "She swam down. It got dark. She stopped. She looked around.",
        "He heard a sound. It came from below. He stopped swimming. He listened.",
        "The water changed. It got colder. It got darker. She slowed down.",
        "She found the cave. She looked inside. It was dark. She did not go in.",
        "He reached the bottom. He looked around. He saw something. He swam closer.",
        "The rope went down into the dark. She grabbed it. She followed it. She wished she had not.",
        "He surfaced. He breathed. He went back down. He went deeper this time.",
        "She saw the shape. It was below her. It did not move. She did not move either.",
        "The light faded. The water grew black. She could not see her own hand. She kept going.",
        "He touched the wreck. The metal was cold. Something moved inside. He pulled his hand back.",
      ],
      advanced: [
        "She checked her gauge. The depth was greater than expected. She checked it again. The number had not changed.",
        "He entered the cave. The passage was narrow. He moved slowly. The passage opened into a large chamber.",
        "She descended past the reef. The coral stopped. The rock dropped away. There was nothing below but dark water.",
        "He signalled to his partner. His partner did not respond. He turned. His partner was gone.",
        "She found the object on the seafloor. It was not natural. It was not on the charts. She photographed it.",
        "He followed the current. It led him away from the group. He stopped. He could not see the others.",
        "She pressed her light against the porthole. The room inside was intact. There was a chair. Someone had left a coat on it.",
        "He reached the marked depth. Nothing was there. He went deeper. He found it at twice the marked depth.",
        "She heard the sound through the water. It was rhythmic. It was not mechanical. She turned off her light.",
        "He noted the temperature drop. He checked the map. He was not where he thought he was.",
      ],
    },

    "literary-devices": {
      beginner: [
        "The water was dark below her.",
        "He could not see the bottom.",
        "The fish swam past without stopping.",
        "She held her breath and looked down.",
        "The water was cold and quiet.",
        "He floated above the deep part.",
        "Something moved in the water below.",
        "She could hear sounds under the surface.",
        "The light did not reach the bottom.",
        "He saw shapes in the dark water.",
      ],
      intermediate: [
        "The water became darker the further down she swam.",
        "He floated above the deep section and looked into it.",
        "The surface of the water was calm but below it was not.",
        "She could hear sounds coming from far down in the water.",
        "The fish moved in a large group through the dark water.",
        "He pressed his face to the glass and looked at what was below.",
        "The light from above grew thin as she descended.",
        "Something large passed beneath the boat in the night.",
        "She swam to the edge of the drop-off and looked over.",
        "The water below the reef was a different colour entirely.",
      ],
      advanced: [
        "The water changed at a certain depth, and not only in temperature.",
        "She descended past the reef into water that felt different in every way.",
        "The sound she had heard once she heard again at twice the depth.",
        "He pressed himself against the rock and watched the shape pass below.",
        "The seafloor, when she finally reached it, was not what she had expected.",
        "She had been told the deep was empty, but she knew now that was wrong.",
        "He looked back toward the surface and could no longer see it.",
        "The creature passed close enough that she felt the movement of the water it displaced.",
        "She had come for answers and found only larger questions waiting in the dark.",
        "The pressure at this depth was not something she had accounted for.",
      ],
    },

    "paragraph-cohesion": {
      beginner: [
        "She went in the water. It was Tuesday. A fish swam past. She liked swimming. The water was blue.",
        "He looked down. His shoes were wet. The water was deep. He had toast for breakfast. He did not jump.",
        "She held her breath. The sun was out. She went under. Her bag was on the beach. She came back up.",
        "The water was cold. He liked cold things. He went in anyway. A bird flew past. He swam around.",
        "She saw something below. She was hungry. It was big. Her towel was on the rock. She swam away.",
        "He was near the edge. It was a hot day. The water looked dark. He had a red hat. He did not go in.",
        "The fish was strange. She had seen fish before. It had no eyes. Lunch was soon. It swam away.",
        "He touched the bottom. The sand was soft. His mum called out. He liked the feel of it. He came up.",
        "She heard a sound. It came from below. She liked sounds. It was low and long. She swam to shore.",
        "The boat rocked. Something was below it. He was reading a book. The water was dark. He looked over the side.",
      ],
      intermediate: [
        "She swam to the drop-off. She had been swimming since she was four. The water changed colour there. Her goggles were foggy. She looked down.",
        "He held his breath and went under. The school carnival was next week. He could see something on the bottom. He was a strong swimmer. He went closer.",
        "The water was cold at the bottom. She had forgotten her wetsuit. Something moved near the cave entrance. She had homework due. She watched it carefully.",
        "He surfaced and took a breath. The boat was further away than he expected. He could hear music from the shore. His legs were tired. He started swimming back.",
        "She found the cave under the ledge. It was her second dive of the day. The entrance was narrow. Her parents were watching from above. She went in anyway.",
        "He saw the shape below and stopped. He had read about this kind of thing. It was too large to be a fish. The water was very clear. He did not tell the others.",
        "She pressed her hand against the rock. The surface was rough. There was something carved into it. She needed to get back to the surface. She looked more carefully.",
        "He checked his watch. The reading on his gauge was lower than he expected. He had been down for twelve minutes. The current had shifted. He began his ascent.",
        "She reached the bottom and looked around. The seafloor was flat and featureless. Then she saw it. Her air was running low. She swam toward it anyway.",
        "He floated above the deep section and did not move. His partner was already on the surface. He could see something far below. The light was fading. He made a decision.",
      ],
      advanced: [
        "She identified the formation on the seafloor as artificial. Her certification only covered recreational depths. The structure extended further than her light could reach. Her report was due Friday. She photographed what she could.",
        "He had been briefed on the location but not on what the location contained. His equipment was rated for this depth. The object on the seafloor was not on any record he had access to. He had an early flight the next morning. He took a sample.",
        "The current pulled her south. She had accounted for a northern current. Her navigation assumed the charted conditions. The depth below her was three times what the chart indicated. She adjusted her bearing.",
        "She entered the wreck through the port side. The starboard entry was blocked by silt. The interior was intact but dark. She had a spare light. The main chamber was the third door on the left.",
        "He surfaced at the wrong marker. The boat was two hundred metres north. He had four minutes of air remaining. The sea was calm. He inflated his signal device.",
        "She noted the temperature anomaly at eighteen metres. It was not consistent with the season. The anomaly extended across the full width of the channel. She had seen this pattern once before. That location had been closed to divers the following year.",
        "He reached the point marked on the map. There was nothing there. The coordinates were correct. He had checked them three times. He descended another ten metres.",
        "The sample she collected dissolved before she reached the surface. She had used the correct container. The depth pressure had not been a factor. She went back down. The formation was gone.",
        "He saw the light before he saw its source. Bioluminescence was not unusual at this depth. This was not bioluminescence. He signalled his partner. His partner had not seen it.",
        "She completed the dive and filed her report. The report was marked incomplete by the review committee. She had included photographs, measurements and samples. The committee did not explain its decision. She requested a second dive and was declined.",
      ],
    },

    "narrative-types": {
      beginner: [
        "She went in the water. She swam down. She came back up.",
        "He looked over the edge. He jumped in. He swam to the bottom.",
        "She held her breath. She went under. She opened her eyes.",
        "He grabbed the rope. He went down. He let go and came up.",
        "She saw something. She swam closer. She stopped.",
        "He kicked his legs. He went deeper. He turned around.",
        "She found a shell. She picked it up. She brought it to the surface.",
        "He got scared. He swam back. He held onto the boat.",
        "She reached the bottom. She looked around. She swam back up.",
        "He went under the wave. He came out the other side. He swam to shore.",
      ],
      intermediate: [
        "She put on her goggles. She jumped in. She swam to the buoy. She looked down.",
        "He took a breath. He went under. He swam to the cave. He looked inside.",
        "She found the rope. She grabbed it. She followed it down. She reached the bottom.",
        "He saw the shape. He stopped swimming. He watched it. He swam the other way.",
        "She checked her air. She had five minutes. She started her ascent. She surfaced.",
        "He entered the cave. He moved through the passage. He reached a chamber. He stopped.",
        "She photographed the coral. She moved along the reef. She reached the drop-off. She looked over.",
        "He signalled his partner. They descended together. They reached the wreck. They went inside.",
        "She heard the sound. She stopped. She turned. She saw nothing. She kept going.",
        "He reached the seafloor. He checked his gauge. He found what he came for. He headed back up.",
      ],
      advanced: [
        "She suited up. She entered the water. She descended to thirty metres. She located the object. She photographed it and began her ascent.",
        "He heard the sound on the third dive. He checked his equipment. He signalled to the surface. He received no reply. He ascended alone.",
        "She entered the wreck through the hull breach. She moved through three compartments. She found the ship's log. She secured it. She exited through the same breach.",
        "He noticed the current shift at fifteen metres. He adjusted his position. He maintained depth. He completed the survey. He surfaced on the eastern marker.",
        "She descended past the reef. She lost visual contact with her partner. She waited at the agreed depth. Her partner did not appear. She completed the ascent solo.",
        "He found the cave at the base of the rock formation. He measured the entrance. He went inside. He found a second chamber. He mapped it and left.",
        "She checked the seafloor coordinates against her dive slate. She was in the right location. She searched for twenty minutes. She found nothing. She surfaced and reviewed the data.",
        "He attached the line at the surface. He followed it to the bottom. He secured the marker. He released the line. He ascended.",
        "She saw the creature at depth. She held her position. It passed within three metres. She did not move. She waited until it was gone and then continued.",
        "He completed the survey. He collected three samples. He photographed the site. He sealed the samples. He handed them to the team on the surface.",
      ],
    },

    "author-stems": {
      beginner: [
        "Without warning, the water ...",
        "All of a sudden, she saw ...",
        "From below, something ...",
        "Before she could stop herself, she ...",
        "Just as he reached the bottom, ...",
        "For a moment, the dark ...",
        "Out of nowhere, a shape ...",
        "Right at that second, she felt ...",
        "Deep below her, something ...",
        "At the edge of the drop-off, ...",
      ],
      intermediate: [
        "Without warning, the water around her ...",
        "Deep below, something was ...",
        "What nobody had expected was that the dark would ...",
        "For a moment, the sound seemed to ...",
        "Long before the others noticed, she had already ...",
        "Below the surface, something ...",
        "With hands that would not stop shaking, she ...",
        "Somewhere between fear and wonder, she realised ...",
        "In the space of a single breath, the water ...",
        "What she had not prepared for was the way the dark ...",
      ],
      advanced: [
        "Somewhere between the surface and the bottom, she ...",
        "What nobody in the boat was willing to say aloud was that ...",
        "Long before she reached the depth on the gauge, she had already understood that ...",
        "With air she could not afford to waste, she ...",
        "Deep below, beneath everything she had assumed about this place, ...",
        "What the chart could not account for was the moment ...",
        "In the years that followed, she would return again and again to ...",
        "Somewhere between the diver she had been and the one she was becoming, ...",
        "Without warning and without any sound to mark it, the water ...",
        "What she had come here to find, after everything, was ...",
      ],
    },

    "information-adders": {
      beginner: [
        "She went under.",
        "He saw something.",
        "The water was cold.",
        "She held her breath.",
        "He swam down.",
        "The fish swam past.",
        "She grabbed the rope.",
        "He came back up.",
        "The water was dark.",
        "She reached the bottom.",
      ],
      intermediate: [
        "She swam toward the cave.",
        "He looked over the edge of the reef.",
        "The shape moved below the surface.",
        "She reached the bottom of the pool.",
        "He held his breath for a long time.",
        "The water grew colder as she descended.",
        "She found something on the seafloor.",
        "He signalled to his partner and waited.",
        "The light faded as she went deeper.",
        "She surfaced before her air ran out.",
      ],
      advanced: [
        "She descended past the marked depth.",
        "He entered the wreck through the hull breach.",
        "The creature passed within metres of her.",
        "She found the object on the seafloor.",
        "He checked his gauge and kept going.",
        "The current shifted without warning.",
        "She photographed the formation and began her ascent.",
        "He lost contact with the surface at twenty metres.",
        "The sound came from directly below her.",
        "She reached the chamber at the end of the passage.",
      ],
    },
  },
};
